xmsgrid: /home/travis/build/Aquaveo/xmsgrid/xmsgrid/ugrid/XmUGrid.cpp File Reference
XmUGrid.cpp File Reference
#include <xmsgrid/ugrid/XmUGrid.h>
#include <set>
#include <unordered_set>
#include <boost/container/flat_set.hpp>
#include <xmscore/misc/XmConst.h>
#include <xmscore/misc/XmError.h>
#include <xmscore/misc/XmLog.h>
#include <xmsgrid/ugrid/XmConvexHull.h>
#include <xmsgrid/ugrid/XmUGridUtils.h>
#include <xmsgrid/ugrid/XmUGrid.t.h>
Classes
class xms::XmUGridImpl
Implementation for XmUGrid.
Namespaces
xms
XMS Namespace.
Functions
BSHP< XmUGrid > TEST_XmUGrid1Left90Tri ()
Builds a 1 cell (left 90 degree triangle) 2D XmUGrid for testing.
BSHP< XmUGrid > TEST_XmUGridSimpleQuad ()
Builds a 2 cell (Quad) 2D XmUGrid for testing.
BSHP< XmUGrid > TEST_XmUGrid2dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
BSHP< XmUGrid > TEST_XmUGrid3dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
BSHP< XmUGrid > TEST_XmUGridHexagonalPolyhedron ()
Builds a 1 cell hexagon with cell type polyhedron.
BSHP< xms::XmUGrid > TEST_XmUBuildQuadUGrid (const int a_rows, const int a_cols)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildQuadUGrid (const int a_rows, const int a_cols, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildHexahedronUgrid (const int a_rows, const int a_cols, const int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildHexahedronUgrid (const int a_rows, const int a_cols, const int a_lays, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildPolyhedronUgrid (const int a_rows, const int a_cols, const int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildPolyhedronUgrid (const int a_rows, const int a_cols, const int a_lays, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuild3DChevronUgrid ()
Builds a UGrid with one 3D Chevron polyhedron.
std::string TestFilesPath ()
Path to test files.
Detailed Description
Copyright
(C) Copyright Aquaveo 2018.
Definition in file XmUGrid.cpp.
Function Documentation
BSHP<xms::XmUGrid> TEST_XmUBuild3DChevronUgrid ()
Builds a UGrid with one 3D Chevron polyhedron.
Returns
Returns the UGrid.
Definition at line 2634 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testGetPlanViewPolygon().
BSHP<xms::XmUGrid> TEST_XmUBuildHexahedronUgrid (const int a_rows, const int a_cols, const int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
Returns
Returns the UGrid.
Definition at line 2469 of file XmUGrid.cpp.
References TEST_XmUBuildHexahedronUgrid().
Referenced by TEST_XmUBuildHexahedronUgrid(), XmUGridUnitTests::testGetAdjacentCell(), XmUGridUnitTests::testGetCellFaceNeighbor(), XmUGridUnitTests::testGetExtents(), XmUGridUnitTests::testGetFacesFromPoint(), and XmUGridUnitTests::testIsCellValidWithPointChange().
BSHP<xms::XmUGrid> TEST_XmUBuildHexahedronUgrid (const int a_rows, const int a_cols, const int a_lays, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
[in] a_origin Point where the UGrid begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 2484 of file XmUGrid.cpp.
References xms::XmUGrid::New().
BSHP<xms::XmUGrid> TEST_XmUBuildPolyhedronUgrid (const int a_rows, const int a_cols, const int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
Returns
Returns the UGrid.
Definition at line 2535 of file XmUGrid.cpp.
References TEST_XmUBuildPolyhedronUgrid().
Referenced by TEST_XmUBuildPolyhedronUgrid(), and XmUGridUnitTests::testLargeUGridLinkSpeed().
BSHP<xms::XmUGrid> TEST_XmUBuildPolyhedronUgrid (const int a_rows, const int a_cols, const int a_lays, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
[in] a_origin Point where the UGrid begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 2550 of file XmUGrid.cpp.
References xms::XmUGrid::New().
BSHP<xms::XmUGrid> TEST_XmUBuildQuadUGrid (const int a_rows, const int a_cols)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
Returns
Returns the UGrid.
Definition at line 2419 of file XmUGrid.cpp.
References TEST_XmUBuildQuadUGrid().
Referenced by TEST_XmUBuildQuadUGrid().
BSHP<xms::XmUGrid> TEST_XmUBuildQuadUGrid (const int a_rows, const int a_cols, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_origin Point where the UGrid begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 2431 of file XmUGrid.cpp.
References xms::XmUGrid::New().
BSHP<XmUGrid> TEST_XmUGrid1Left90Tri ()
Builds a 1 cell (left 90 degree triangle) 2D XmUGrid for testing.
2
| \
|  \
|   \
0----1
Returns
Returns a builder for the UGrid.
Definition at line 2289 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUtilsTests::testReadBasicUGrid(), and XmUGridUtilsTests::testWriteBasicUGrid().
BSHP<XmUGrid> TEST_XmUGrid2dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
Returns
Returns the XmUGrid.
[snip_test_2DShapes]
[snip_test_2DShapes]
Definition at line 2329 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testGetCellDimension(), XmUGridUnitTests::testGetCellEdgeFromEdgeIndex(), XmUGridUnitTests::testGetCellFace(), XmUGridUnitTests::testGetCellNeighbors(), XmUGridUnitTests::testGetCellType(), XmUGridUnitTests::testGetExtents(), XmUGridUnitTests::testGetNumberOfCellEdges(), XmUGridUnitTests::testGetNumberOfCellFaces(), XmUGridUnitTests::testGetPlanViewPolygon(), XmUGridUnitTests::testGetPointCells(), XmUGridUnitTests::testGetPointsOfCell(), XmUGridUtilsTests::testLinear2dWriteThenRead(), and XmUGridUtilsTests::testWriteLinear2dCells().
BSHP<XmUGrid> TEST_XmUGrid3dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
Returns
Returns the XmUGrid.
[snip_test_3DShapes]
[snip_test_3DShapes]
Definition at line 2355 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testGetCellDimension(), XmUGridUnitTests::testGetCellEdgeFromEdgeIndex(), XmUGridUnitTests::testGetCellFace(), XmUGridUnitTests::testGetCellNeighbors(), XmUGridUnitTests::testGetCellType(), XmUGridUnitTests::testGetExtents(), XmUGridUnitTests::testGetFaces(), XmUGridUnitTests::testGetNumberOfCellEdges(), XmUGridUnitTests::testGetNumberOfCellFaces(), XmUGridUnitTests::testGetPlanViewPolygon(), XmUGridUnitTests::testGetPointCells(), XmUGridUnitTests::testGetPointsOfCell(), XmUGridUtilsTests::testLinear3dWriteThenRead(), XmUGridUtilsTests::testWriteLinear3dCells(), XmUGridUtilsTests::testWriteThenReadUGridFile(), and XmUGridUtilsTests::testWriteThenReadUGridFileToAscii().
BSHP<XmUGrid> TEST_XmUGridHexagonalPolyhedron ()
Builds a 1 cell hexagon with cell type polyhedron.
Returns
Returns the UGrid.
Definition at line 2390 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUtilsTests::testReadPolyhedronUGrid(), and XmUGridUtilsTests::testWritePolyhedronUGrid().
BSHP<XmUGrid> TEST_XmUGridSimpleQuad ()
Builds a 2 cell (Quad) 2D XmUGrid for testing.
0-----1-----2
|  0  |  1  |
3-----4-----5
|  2  |  3  |
6-----7-----8
Returns
Returns a builder for the UGrid.
Definition at line 2312 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testCellFunctions(), XmUGridUnitTests::testGetAdjacentCell(), XmUGridUnitTests::testGetAdjacentCellFunctions(), XmUGridUnitTests::testGetAdjacentCellsFromGivenEdge(), XmUGridUnitTests::testGetCellEdgeFromEdgeIndex(), XmUGridUnitTests::testGetCellNeighbors(), XmUGridUnitTests::testGetCellStreamFunctions(), XmUGridUnitTests::testGetCommonCells(), XmUGridUnitTests::testGetEdgesFromPoint(), XmUGridUnitTests::testGetEdgesOfCell(), XmUGridUnitTests::testGetPointsOfCell(), XmUGridUnitTests::testIsCellValidWithPointChange(), and XmUGridUnitTests::testPointFunctions().
std::string TestFilesPath ()
Path to test files.
Returns
Returns path to test files.
Definition at line 2655 of file XmUGrid.cpp.
Referenced by XmUGridUtilsTests::testWriteThenReadUGridFile(), and XmUGridUtilsTests::testWriteThenReadUGridFileToAscii().