var annotated_dup =
[
    [ "xms", "namespacexms.html", "namespacexms" ],
    [ "GeomsXmsngIntermediateTests", "class_geoms_xmsng_intermediate_tests.html", "class_geoms_xmsng_intermediate_tests" ],
    [ "GeomsXmsngUnitTests", "class_geoms_xmsng_unit_tests.html", "class_geoms_xmsng_unit_tests" ],
    [ "GmExtents3dUnitTests", "class_gm_extents3d_unit_tests.html", "class_gm_extents3d_unit_tests" ],
    [ "GmMultiPolyIntersector2IntermediateTests", "class_gm_multi_poly_intersector2_intermediate_tests.html", "class_gm_multi_poly_intersector2_intermediate_tests" ],
    [ "GmMultiPolyIntersectorUnitTests", "class_gm_multi_poly_intersector_unit_tests.html", "class_gm_multi_poly_intersector_unit_tests" ],
    [ "GmPointInPolyTester_gmPointInPolygon2D", "class_gm_point_in_poly_tester__gm_point_in_polygon2_d.html", "class_gm_point_in_poly_tester__gm_point_in_polygon2_d" ],
    [ "GmPointInPolyTester_GmPolygon", "class_gm_point_in_poly_tester___gm_polygon.html", "class_gm_point_in_poly_tester___gm_polygon" ],
    [ "GmPointInPolyUnitTests", "class_gm_point_in_poly_unit_tests.html", "class_gm_point_in_poly_unit_tests" ],
    [ "GmPolygonIntermediateTests", "class_gm_polygon_intermediate_tests.html", "class_gm_polygon_intermediate_tests" ],
    [ "GmPolygonUnitTests", "class_gm_polygon_unit_tests.html", "class_gm_polygon_unit_tests" ],
    [ "GmPolyLinePtRedistributerUnitTests", "class_gm_poly_line_pt_redistributer_unit_tests.html", "class_gm_poly_line_pt_redistributer_unit_tests" ],
    [ "PtSearchUnitTests", "class_pt_search_unit_tests.html", "class_pt_search_unit_tests" ],
    [ "TrAutoFixFourTrianglePtsUnitTests", "class_tr_auto_fix_four_triangle_pts_unit_tests.html", "class_tr_auto_fix_four_triangle_pts_unit_tests" ],
    [ "TrBreaklineAdderUnitTests", "class_tr_breakline_adder_unit_tests.html", "class_tr_breakline_adder_unit_tests" ],
    [ "TriSearchUnitTests", "class_tri_search_unit_tests.html", "class_tri_search_unit_tests" ],
    [ "TrOuterTriangleDeleterUnitTests", "class_tr_outer_triangle_deleter_unit_tests.html", "class_tr_outer_triangle_deleter_unit_tests" ],
    [ "TrTinUnitTests", "class_tr_tin_unit_tests.html", "class_tr_tin_unit_tests" ],
    [ "TrTriangulatorPointsUnitTests", "class_tr_triangulator_points_unit_tests.html", "class_tr_triangulator_points_unit_tests" ],
    [ "XmEdgeUnitTests", "class_xm_edge_unit_tests.html", "class_xm_edge_unit_tests" ],
    [ "XmUGridUnitTests", "class_xm_u_grid_unit_tests.html", "class_xm_u_grid_unit_tests" ],
    [ "XmUGridUtilsTests", "class_xm_u_grid_utils_tests.html", "class_xm_u_grid_utils_tests" ]
];