xmsgrid: XmUGridUtilsTests Class Reference
XmUGridUtilsTests Class Reference
Tests for XmUGrid utility functions.
#include <XmUGridUtils.t.h>
Public Member Functions
void testWriteEmptyUGrid ()
Test writing an ASCII file for an empty UGrid.
void testWriteBasicUGrid ()
Test writing an ASCII file for a single triangle UGrid.
void testWritePolyhedronUGrid ()
Test writing an ASCII file for a single polyhedron UGrid.
void testWriteLinear2dCells ()
Test writing an ASCII file for UGrid with supported 1D and 2D linear cell types.
void testWriteLinear3dCells ()
Test writing an ASCII file for UGrid with supported 1D and 2D linear cell types.
void testReadEmptyUGridAsciiFile ()
Test reading an ASCII file for an empty UGrid.
void testReadBasicUGrid ()
Test reading an ASCII file for a single triangle UGrid.
void testReadPolyhedronUGrid ()
Test reading an ASCII file for a single triangle UGrid.
void testLinear2dWriteThenRead ()
Test reading an ASCII file for a single triangle UGrid.
void testLinear3dWriteThenRead ()
Test reading an ASCII file for a single triangle UGrid.
void testWriteThenReadUGridFile ()
Test reading from file.
void testWriteThenReadUGridFileToAscii ()
[snip_test_WriteReadAscii]
void testReadVersion1Dot0File ()
[snip_test_WriteReadAscii]
void testWriteThenReadUGridBinary ()
Test writing then reading an XmUGrid binary file.
void testCellStringToEnum ()
Test conversion between cell type string and cell type enum.
void testLargeUGridBinarySpeed ()
Tests creating a large UGrid and checks the time spent.
void testReadReadyAtNextLine ()
Test reading XmUGrid to make sure it doesn't read the whole file. Should leave stream at next line after XmUGrid contents.
Detailed Description
Tests for XmUGrid utility functions.
Tests XmUGrids.
Definition at line 22 of file XmUGridUtils.t.h.
Member Function Documentation
testWriteThenReadUGridFileToAscii()
void XmUGridUtilsTests::testWriteThenReadUGridFileToAscii ()
[snip_test_WriteReadAscii]
Test reading from file.
Definition at line 1208 of file XmUGridUtils - Copy.cpp.
References xms::TEST_XmUGrid3dLinear(), xms::XmReadUGridFromAsciiFile(), and xms::XmWriteUGridToAsciiFile().
The documentation for this class was generated from the following files:
/home/conan/xmsgrid/ugrid/XmUGridUtils.t.h
/home/conan/xmsgrid/ugrid/XmUGridUtils - Copy.cpp
/home/conan/xmsgrid/ugrid/XmUGridUtils.cpp