xmsgrid: XmUGridUnitTests Class Reference
XmUGridUnitTests Class Reference
Tests XmUGrids.
Public Member Functions
void testUGridStreams ()
[snip_test_UGrid_Streams]
void testGetSetPoint ()
[snip_test_UGrid_Streams]
void testGetCellCellstream ()
Test Getting a cell stream.
void testGetCellType ()
Test getting number of points, cells, and cell type.
void testGetCellDimension ()
Test getting dimension of single cells and all cells.
void testGetExtents ()
Test getting the extents of a UGrid.
void testGetCellEdgeCount ()
Test getting edges of single cells.
void testGetCell3dFaceCount ()
[snip_test_GetNumberOfCellFaces]
void testGetCell3dFacePointCount ()
[snip_test_GetNumberOfCellFaces]
void testGetPointAdjacentCellsSimple ()
Test getting the cells attached to points.
void testGetPointAdjacentCells ()
Test getting cells adjacent to a point.
void testGetCellPoints ()
Test getting a vector of point indices for a cell.
void testGetCellEdge ()
Test iterating through the edges of cells.
void testGetPointsAdjacentCells ()
Test retrieving common cells from points.
void testGetCellAdjacentCells ()
[snip_test_GetCellAdjacentCells]
void testGetCellEdgeAdjacentCells ()
[snip_test_GetCellAdjacentCells]
void testEdgeAdjacentCells ()
Test retrieving Adjacent Cell.
void testGetCell3dFacePoints ()
Test retrieving Cell Face.
void testGetCell3dFaceAdjacentCell ()
[snip_test_GetCell3dFaceAdjacentCell]
void testGetPointAdjacentPoints ()
[snip_test_GetCell3dFaceAdjacentCell]
void testGetCellPlanViewPolygon ()
[snip_test_GetPointAdjacentPoints]
void testGetCellPlanViewPolygonMultiSideFace ()
[snip_test_GetCellPlanViewPolygon]
void testIsCellValidWithPointChange ()
Test validating a cell for a changed point.
void testPointFunctions ()
[snip_test_PointFunctions]
void testCellFunctions ()
[snip_test_PointFunctions]
void testCellstreamFunctions ()
Test various cell functions.
void testCellEdgeAdjacentCellFunctions ()
Test all get adjacent cell functions.
void testCellEdges ()
Test various cell functions.
void testCell3dFaceFunctions ()
Test various get face functions.
void testGetCell3dFaceOrientationConcaveCell ()
[snip_test_Cell3dFaceFunctions]
void testCell3dFunctionCaching ()
Test caching to speed up a few 3D cell getters.
void testLargeUGridLinkSpeed ()
Tests creating a large UGrid and checks the time spent.
Detailed Description
Tests XmUGrids.
Definition at line 30 of file XmUGrid.t.h.
Member Function Documentation
testCell3dFaceFunctions()
void XmUGridUnitTests::testCell3dFaceFunctions ()
Test various get face functions.
[snip_test_CellEdges] [snip_test_Cell3dFaceFunctions]
Definition at line 5165 of file XmUGrid.cpp.
References xms::TEST_XmUGrid3dLinear().
testCellEdgeAdjacentCellFunctions()
void XmUGridUnitTests::testCellEdgeAdjacentCellFunctions ()
Test all get adjacent cell functions.
[snip_test_CellstreamFunctions] [snip_test_CellEdgeAdjacentCellFunctions]
Definition at line 5102 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testCellEdges()
void XmUGridUnitTests::testCellEdges ()
Test various cell functions.
[snip_test_CellEdgeAdjacentCellFunctions] [snip_test_CellEdges]
Definition at line 5145 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testCellFunctions()
void XmUGridUnitTests::testCellFunctions ()
[snip_test_PointFunctions]
[snip_test_CellFunctions] Test various cell functions
Definition at line 5029 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testCellstreamFunctions()
void XmUGridUnitTests::testCellstreamFunctions ()
Test various cell functions.
[snip_test_CellFunctions] [snip_test_CellstreamFunctions]
Definition at line 5076 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testGetCell3dFaceAdjacentCell()
void XmUGridUnitTests::testGetCell3dFaceAdjacentCell ()
[snip_test_GetCell3dFaceAdjacentCell]
Test retrieving Cell Face Neighbor
Definition at line 4655 of file XmUGrid.cpp.
References xms::TEST_XmUBuildHexahedronUgrid().
testGetCell3dFaceCount()
void XmUGridUnitTests::testGetCell3dFaceCount ()
[snip_test_GetNumberOfCellFaces]
Test getting edges of single cells.
Definition at line 3924 of file XmUGrid.cpp.
References xms::TEST_XmUGrid2dLinear(), and xms::TEST_XmUGrid3dLinear().
testGetCell3dFaceOrientationConcaveCell()
void XmUGridUnitTests::testGetCell3dFaceOrientationConcaveCell ()
[snip_test_Cell3dFaceFunctions]
Test face orientation for concave cell where a triangle from the first two points in the top face to the centroid create a triangle with a normal pointing down rather than up.
Definition at line 5272 of file XmUGrid.cpp.
References xms::XmUGrid::New().
testGetCell3dFacePointCount()
void XmUGridUnitTests::testGetCell3dFacePointCount ()
[snip_test_GetNumberOfCellFaces]
Test getting the number of face points for a cell face.
Definition at line 3963 of file XmUGrid.cpp.
References xms::TEST_XmUGrid2dLinear(), and xms::TEST_XmUGrid3dLinear().
testGetCellAdjacentCells()
void XmUGridUnitTests::testGetCellAdjacentCells ()
[snip_test_GetCellAdjacentCells]
Test retrieving Cell Neighbors
Definition at line 4365 of file XmUGrid.cpp.
References xms::TEST_XmUGrid2dLinear(), xms::TEST_XmUGrid3dLinear(), and xms::TEST_XmUGridSimpleQuad().
testGetCellEdge()
void XmUGridUnitTests::testGetCellEdge ()
Test iterating through the edges of cells.
[snip_test_GetCellEdgeFromEdgeIndex2D]
[snip_test_GetCellEdgeFromEdgeIndex2D]
[snip_test_GetCellEdgeFromEdgeIndex3D]
[snip_test_GetCellEdgeFromEdgeIndex3D]
Definition at line 4172 of file XmUGrid.cpp.
References xms::TEST_XmUGrid2dLinear(), xms::TEST_XmUGrid3dLinear(), and xms::TEST_XmUGridSimpleQuad().
testGetCellEdgeAdjacentCells()
void XmUGridUnitTests::testGetCellEdgeAdjacentCells ()
[snip_test_GetCellAdjacentCells]
Test retrieving Adjacent Cell
Definition at line 4457 of file XmUGrid.cpp.
References xms::TEST_XmUBuildHexahedronUgrid(), and xms::TEST_XmUGridSimpleQuad().
testGetCellPlanViewPolygon()
void XmUGridUnitTests::testGetCellPlanViewPolygon ()
[snip_test_GetPointAdjacentPoints]
[snip_test_GetCellPlanViewPolygon] Test getting the plan view polygon of a cell.
Definition at line 4809 of file XmUGrid.cpp.
References xms::TEST_XmUBuild3DChevronUgrid(), xms::TEST_XmUGrid2dLinear(), and xms::TEST_XmUGrid3dLinear().
testGetCellPlanViewPolygonMultiSideFace()
void XmUGridUnitTests::testGetCellPlanViewPolygonMultiSideFace ()
[snip_test_GetCellPlanViewPolygon]
Test getting the plan view points of a cell.
Definition at line 4877 of file XmUGrid.cpp.
References xms::XmUGrid::New().
testGetPointAdjacentPoints()
void XmUGridUnitTests::testGetPointAdjacentPoints ()
[snip_test_GetCell3dFaceAdjacentCell]
[snip_test_GetPointAdjacentPoints] Test GetPointAdjacentPoints and GetPointAdjacentLocations.
Definition at line 4768 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testGetSetPoint()
void XmUGridUnitTests::testGetSetPoint ()
[snip_test_UGrid_Streams]
Test Getting a point
[snip_test_NewOperator]
[snip_test_NewOperator]
Definition at line 3672 of file XmUGrid.cpp.
References xms::XmUGrid::New().
testPointFunctions()
void XmUGridUnitTests::testPointFunctions ()
[snip_test_PointFunctions]
Test various point functions
Definition at line 4969 of file XmUGrid.cpp.
References xms::TEST_XmUGridSimpleQuad().
testUGridStreams()
void XmUGridUnitTests::testUGridStreams ()
[snip_test_UGrid_Streams]
Test XmUGrid point and cell streams.
Definition at line 3614 of file XmUGrid.cpp.
References xms::XmUGrid::IsValidCellstream(), and xms::XmUGrid::New().
The documentation for this class was generated from the following files:
/home/conan/xmsgrid/ugrid/XmUGrid.t.h
/home/conan/xmsgrid/ugrid/XmUGrid.cpp