xmsgrid: xms::XmUGridImpl Class Reference
xms::XmUGridImpl Class Reference
Implementation for XmUGrid.
Public Member Functions
XmUGridImpl ()
Default constructor.
virtual bool GetModified () const override
Returns the modified flag. Gets set when points or cells get changed.
virtual void SetUnmodified () override
Resets the modified flag to false.
virtual void SetUseCache (bool a_useCache) override
Turn on or off use of caching.
virtual int GetPointCount () const override
Get the number of points.
virtual const VecPt3d & GetLocations () const override
Get vector of UGrid points.
virtual void SetLocations (const VecPt3d &a_locations) override
Set UGrid points.
virtual Pt3d GetPointLocation (const int a_pointIdx) const override
Get the point.
virtual bool SetPointLocation (const int a_pointIdx, const Pt3d &a_point) override
Set the point.
virtual Pt3d GetPointXy0 (const int a_pointIdx) const override
Get the X, Y location of a point.
virtual VecPt3d GetPointsLocations (const VecInt &a_points) const override
Convert a vector of point indices into a vector of point 3d.
virtual void GetExtents (Pt3d &a_min, Pt3d &a_max) const override
Get extents of all points in UGrid.
virtual VecInt GetPointAdjacentCells (const int a_pointIdx) const override
Get the cells that are associated with the specified point.
virtual void GetPointAdjacentCells (const int a_pointIdx, VecInt &a_adjacentCells) const override
Get the cells that are associated with the specified point.
virtual VecInt GetPointsAdjacentCells (const VecInt &a_points) const override
Gets the common cells from a vector of points.
virtual void GetPointsAdjacentCells (const int *a_pointIdxs, int a_numpointIdxs, VecInt &a_commonCellIdxs) const
Gets the common cells from a vector of points.
virtual void GetPointsAdjacentCells (const VecInt &a_points, VecInt &a_commonCellIdxs) const override
Gets the cells adjacent to all of a vector of points.
virtual void GetPointsAdjacentCells (const int a_pointIdx1, const int a_pointIdx2, VecInt &a_commonCellIdxs) const override
Gets the cells adjacent to both of the two points.
virtual bool IsValidPointChange (const int a_changedPtIdx, const Pt3d &a_newPosition) const override
Determine whether adjacent cells are valid after a point is moved.
virtual int GetCellCount () const override
Get the number of cells.
virtual int GetCellPointCount (const int a_cellIdx) const override
Get the number of cell points (including polyhedron).
virtual VecInt GetCellPoints (const int a_cellIdx) const override
Get the points of a cell (including polyhedron)
virtual bool GetCellPoints (const int a_cellIdx, VecInt &a_cellPoints) const override
Get the points of a cell.
virtual void GetCellLocations (const int a_cellIdx, VecPt3d &a_cellLocations) const override
Get locations of cell points.
virtual XmUGridCellType GetCellType (const int a_cellIdx) const override
Get the cell type of a specified cell.
virtual std::vector< int > GetDimensionCounts () const override
Count all number of the cells with each dimension (0, 1, 2, 3)
virtual int GetCellDimension (const int a_cellIdx) const override
Get the dimension of the specified cell.
virtual void GetCellExtents (const int a_cellIdx, Pt3d &a_min, Pt3d &a_max) const override
Get the extents of the given cell.
virtual const VecInt & GetCellstream () const override
Get cell stream vector for the entire UGrid.
virtual bool SetCellstream (const VecInt &a_cellstream) override
Set the ugrid cells for the entire UGrid using a cell stream.
virtual bool GetCellCellstream (const int a_cellIdx, VecInt &a_cellstream) const override
Get cell stream vector for a single cell.
virtual VecInt GetCellAdjacentCells (const int a_cellIdx) const override
Get the cells neighboring a cell (cells associated with any of it's points)
virtual void GetCellAdjacentCells (const int a_cellIdx, VecInt &a_cellNeighbors) const override
Get the cells neighboring a cell (cells associated with any of it's points)
virtual bool GetCellPlanViewPolygon (int a_cellIdx, VecPt3d &a_polygon) const override
Get a plan view polygon of a specified cell.
virtual bool GetCellCentroid (int a_cellIdx, Pt3d &a_centroid) const override
Get the centroid location of a cell.
virtual int GetCellEdgeCount (const int a_cellIdx) const override
Get the number of edges for a cell.
virtual XmEdge GetCellEdge (const int a_cellIdx, const int a_edgeIdx) const override
Get the points of a cell.
virtual VecInt GetCellEdgeAdjacentCells (const int a_cellIdx, const int a_edgeIdx) const override
Get the index of the adjacent cells (that shares the same cell edge)
virtual void GetCellEdgeAdjacentCells (const int a_cellIdx, const int a_edgeIdx, VecInt &a_adjacentCellIdxs) const override
Get the index of the adjacent cells (that shares the same cell edge)
virtual int GetCell2dEdgeAdjacentCell (const int a_cellIdx, const int a_edgeIdx) const override
Get the index of the adjacent cells (that shares the same cell edge)
virtual void GetEdgeAdjacentCells (const XmEdge &a_edge, VecInt &a_adjacentCellIdxs) const override
Get the indices of the adjacent cells (that shares the same cell edge)
virtual VecInt GetEdgeAdjacentCells (const XmEdge &a_edge) const override
Get the index of the adjacent cells (that shares the same cell edge)
virtual std::vector< XmEdge > GetCellEdges (const int a_cellIdx) const override
Get the Edges of a cell.
virtual void GetCellEdges (const int a_cellIdx, std::vector< XmEdge > &a_edges) const override
Get the Edges of a cell.
virtual void GetPointAdjacentPoints (int a_pointIdx, VecInt &a_edgePoints) const override
Given a point gets point indices attached to the point by an edge.
virtual void GetPointAdjacentLocations (int a_pointIdx, VecPt3d &a_edgePoints) const override
Given a point gets point locations attached to the point by an edge.
virtual int GetCell3dFaceCount (const int a_cellIdx) const override
Get the number of cell faces for given cell.
virtual int GetCell3dFacePointCount (const int a_cellIdx, const int a_faceIdx) const override
Get the number of face points for a given cell and face.
virtual VecInt GetCell3dFacePoints (const int a_cellIdx, const int a_faceIdx) const override
Get the cell face for given cell and face index.
virtual void GetCell3dFacePoints (const int a_cellIdx, const int a_faceIdx, VecInt &a_facePtIdxs) const override
Get the cell face for given cell and face index.
virtual VecInt2d GetCell3dFacesPoints (const int a_cellIdx) const override
Get the faces of a cell.
virtual int GetCell3dFaceAdjacentCell (const int a_cellIdx, const int a_faceIdx) const override
Get the cell face neighbors for given cell and face index.
virtual bool GetCell3dFaceAdjacentCell (const int a_cellIdx, const int a_faceIdx, int &a_neighborCell, int &a_neighborFace) const override
Get the cell face neighbors for given cell and face index.
virtual XmUGridFaceOrientation GetCell3dFaceOrientation (int a_cellIdx, int a_faceIdx) const override
Get the orientation of the face of a vertically prismatic cell.
Public Member Functions inherited from xms::XmUGrid
virtual ~XmUGrid ()
Destructor.
Private Types
enum XmUGridCacheHolder { NEEDS_CALCULATION = -2 }
Constant for when a cached integer item needs to be calculated.
Private Member Functions
void UpdateLinks ()
Update internal links to navigate between associated points and cells.
void UpdateCellLinks ()
Update internal link from cells to cell stream index.
void UpdatePointLinks ()
Update internal links from points to associated cells.
void SetModified ()
Sets the modified flag to true.
bool IsCellValidWithPointChange (const int a_cellIdx, const int a_changedPtIdx, const Pt3d &a_newPosition) const
Determine whether a cell is valid after a point is moved.
bool IsValidCellIdx (const int a_cellIdx) const
Determine if a cell index is valid.
int GetNumberOfItemsForCell (const int a_cellIdx) const
Get number of items given cell. For polyhedron number of items is number of faces. For other cell types it is number of points.
void GetCellCellstream (const int a_cellIdx, const int **a_start, int &a_length) const
Internal function to get start of cell stream for an individual cell. Returns nullptr and zero length for invalid cell index.
int GetNumberOfPolyhedronEdges (const int a_cellIdx) const
Get the number of edges for a polyhedron cell.
bool GetPlanViewPolygon2d (int a_cellIdx, VecPt3d &a_polygon) const
Get a plan view polygon of a specified 2D cell.
bool GetPlanViewPolygon3d (int a_cellIdx, VecPt3d &a_polygon) const
Get a plan view polygon of a specified 3D cell.
bool IsFaceSide (const VecInt &a_facePts) const
Get whether the cell face is of a side orientation. Only works for plan view prismatic cells.
bool GetCellXySegments (int cellIdx, VecPt3d &a_segments) const
Get the XY segments of a cell.
void GetEdgesOfFace (const VecInt &a_face, std::vector< XmEdge > &a_edges) const
Get the edges of a cell given a face.
bool DoEdgesCrossWithPointChange (const int a_changedPtIdx, const Pt3d &a_newPosition, const std::vector< XmEdge > &a_edges) const
Gets whether or not edges cross with a point change.
void GetExtentsFromPoints (const VecPt3d &a_points, Pt3d &a_min, Pt3d &a_max) const
Function to get the extents from a list of points. Will be removed after geometry library is built.
bool GetFaceXySegments (int a_cellIdx, int a_faceIdx, VecPt3d &a_segments) const
Get the Xy locations of Face Points.
void CalculateCacheValues () const
Calculate cached values for faster lookup.
void ClearCacheValues ()
Clear cached so they will be recalculated.
int GetCell3dFaceCountNoCache (const int a_cellIdx) const
Get the number of cell faces for given cell.
int GetCell3dFaceAdjacentCellNoCache (const int a_cellIdx, const int a_faceIdx) const
Get the cell face neighbors for given cell and face index.
XmUGridFaceOrientation GetCell3dFaceOrientationNoCache (int a_cellIdx, int a_faceIdx) const
Get the orientation of the face of a vertically prismatic cell.
Static Private Member Functions
static int DimensionFromCellType (const XmUGridCellType a_cellType)
Get the dimension given the cell type (0d, 1d, 2d, or 3d).
static void GetUniquePointsFromPolyhedronCellstream (const VecInt &a_cellstream, const int a_numCellItems, int &a_currIdx, VecInt &a_uniquePoints, VecInt &a_cellMask)
Get the unique points in a flat set.
static bool GetUniquePointsFromPolyhedronSingleCellstream (const VecInt &a_cellstream, VecInt &a_cellPoints)
Get the unique points for cell stream of a single polyhedron cell.
static void GetUniqueEdgesFromPolyhedronCellstream (const int *a_start, int &a_length, boost::container::flat_set< XmEdge > &a_cellEdges, int &a_currIdx)
Get the unique edges in a flat set for a given polyhedron.
Private Attributes
VecPt3d m_points
UGrid points.
VecInt m_cellstream
UGrid cell stream.
VecInt m_cellIdxToStreamIdx
Indexes for each cell in the cell stream.
VecInt m_pointsToCells
VecInt m_pointIdxToPointsToCells
bool m_modified = false
Has UGrid been modified since last SetUnmodified call?
bool m_useCache = true
Are we using caching for some calls?
VecInt m_numberOfFaces
Cache for number of cell faces.
VecInt m_cellFaceOffset
Cache for offset to m_faceOrientation and m_faceNeighbor.
VecInt m_faceOrientation
For vertically prismatic cell is face top, side, bottom.
VecInt m_faceNeighbor
Cache for Face neighbor.
VecInt m_cellDimensionCounts
Cache for cell dimension counts.
Additional Inherited Members
Static Public Member Functions inherited from xms::XmUGrid
static BSHP< XmUGrid > New (const VecPt3d &a_points, const VecInt &a_cellstream)
Create a new XmUGrid.
static BSHP< XmUGrid > New ()
Create a new XmUGrid.
static bool IsValidCellstream (const VecInt &a_cellstream)
Check a cell stream to make sure it's valid. Compares cell type against expected number of points.
Protected Member Functions inherited from xms::XmUGrid
XmUGrid ()
Constructor.
Detailed Description
Implementation for XmUGrid.
Implementation for XmUGrid which provides geometry for an unstructured grid.
Definition at line 55 of file XmUGrid.cpp.
Member Enumeration Documentation
XmUGridCacheHolder
enum xms::XmUGridImpl::XmUGridCacheHolder private
Constant for when a cached integer item needs to be calculated.
Enumerator
NEEDS_CALCULATION
Cached value needs to be calculated.
Definition at line 207 of file XmUGrid.cpp.
Member Function Documentation
DimensionFromCellType()
int xms::XmUGridImpl::DimensionFromCellType (const XmUGridCellType a_cellType) static private
Get the dimension given the cell type (0d, 1d, 2d, or 3d).
Parameters
[in] a_cellType the cell type
Returns
the dimension of the cell type
Definition at line 2478 of file XmUGrid.cpp.
Referenced by GetCellDimension().
DoEdgesCrossWithPointChange()
bool xms::XmUGridImpl::DoEdgesCrossWithPointChange (const int a_changedPtIdx, const Pt3d & a_newPosition, const std::vector< XmEdge > & a_edges) const private
Gets whether or not edges cross with a point change.
Parameters
[out] a_edges The edges to check
[in] a_changedPtIdx index of the point to be changed
[in] a_newPosition location the point is to be moved to
Returns
whether the edges cross
Definition at line 1708 of file XmUGrid.cpp.
References xms::DoLineSegmentsCross(), and GetPointLocation().
Referenced by IsCellValidWithPointChange().
GetCell2dEdgeAdjacentCell()
int xms::XmUGridImpl::GetCell2dEdgeAdjacentCell (const int a_cellIdx, const int a_edgeIdx) const override virtual
Get the index of the adjacent cells (that shares the same cell edge)
Parameters
[in] a_cellIdx the index of the cell
[in] a_edgeIdx the index of the edge
Returns
index of the adjacent cell (or -1 if none).
Implements xms::XmUGrid.
Definition at line 1900 of file XmUGrid.cpp.
References GetCellEdgeAdjacentCells().
GetCell3dFaceAdjacentCell() [1/2]
int xms::XmUGridImpl::GetCell3dFaceAdjacentCell (const int a_cellIdx, const int a_faceIdx) const override virtual
Get the cell face neighbors for given cell and face index.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
Returns
a cell index of the neighbor
Implements xms::XmUGrid.
Definition at line 2177 of file XmUGrid.cpp.
References CalculateCacheValues(), GetCell3dFaceAdjacentCellNoCache(), GetCell3dFaceCount(), m_cellFaceOffset, m_faceNeighbor, m_useCache, and NEEDS_CALCULATION.
Referenced by GetCell3dFaceAdjacentCell().
GetCell3dFaceAdjacentCell() [2/2]
bool xms::XmUGridImpl::GetCell3dFaceAdjacentCell (const int a_cellIdx, const int a_faceIdx, int & a_neighborCell, int & a_neighborFace) const override virtual
Get the cell face neighbors for given cell and face index.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
[in] a_neighborCell the index of the neighboring cell
[in] a_neighborFace the face index of the neighboring cell adjacent to the given face
Returns
a cell index of the neighbor
Implements xms::XmUGrid.
Definition at line 2218 of file XmUGrid.cpp.
References GetCell3dFaceAdjacentCell(), GetCell3dFaceCount(), and GetCell3dFacePoints().
GetCell3dFaceAdjacentCellNoCache()
int xms::XmUGridImpl::GetCell3dFaceAdjacentCellNoCache (const int a_cellIdx, const int a_faceIdx) const private
Get the cell face neighbors for given cell and face index.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
Returns
a cell index of the neighbor
Definition at line 2962 of file XmUGrid.cpp.
References GetCell3dFacePoints(), and GetPointsAdjacentCells().
Referenced by GetCell3dFaceAdjacentCell().
GetCell3dFaceCount()
int xms::XmUGridImpl::GetCell3dFaceCount (const int a_cellIdx) const override virtual
Get the number of cell faces for given cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
the count of cell faces
Implements xms::XmUGrid.
Definition at line 2015 of file XmUGrid.cpp.
References CalculateCacheValues(), GetCell3dFaceCountNoCache(), IsValidCellIdx(), m_numberOfFaces, and m_useCache.
Referenced by GetCell3dFaceAdjacentCell(), GetCell3dFaceOrientation(), GetCell3dFacesPoints(), and GetCellXySegments().
GetCell3dFaceCountNoCache()
int xms::XmUGridImpl::GetCell3dFaceCountNoCache (const int a_cellIdx) const private
Get the number of cell faces for given cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
the count of cell faces
Definition at line 2934 of file XmUGrid.cpp.
References GetCellType(), GetNumberOfItemsForCell(), and IsValidCellIdx().
Referenced by CalculateCacheValues(), and GetCell3dFaceCount().
GetCell3dFaceOrientation()
XmUGridFaceOrientation xms::XmUGridImpl::GetCell3dFaceOrientation (int a_cellIdx, int a_faceIdx) const override virtual
Get the orientation of the face of a vertically prismatic cell.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
Returns
The orientation of the face (TOP, BOTTOM, SIDE, UNKNOWN).
Implements xms::XmUGrid.
Definition at line 2267 of file XmUGrid.cpp.
References CalculateCacheValues(), GetCell3dFaceCount(), GetCell3dFaceOrientationNoCache(), m_cellFaceOffset, m_faceOrientation, m_useCache, and NEEDS_CALCULATION.
GetCell3dFaceOrientationNoCache()
XmUGridFaceOrientation xms::XmUGridImpl::GetCell3dFaceOrientationNoCache (int a_cellIdx, int a_faceIdx) const private
Get the orientation of the face of a vertically prismatic cell.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
Returns
The orientation of the face (TOP, BOTTOM, SIDE, UNKNOWN).
Definition at line 2989 of file XmUGrid.cpp.
Referenced by GetCell3dFaceOrientation().
GetCell3dFacePointCount()
int xms::XmUGridImpl::GetCell3dFacePointCount (const int a_cellIdx, const int a_faceIdx) const override virtual
Get the number of face points for a given cell and face.
Parameters
[in] a_cellIdx The cell
[in] a_faceIdx The face
Returns
The number of face points or -1 if invalid face or cell index.
Implements xms::XmUGrid.
Definition at line 2035 of file XmUGrid.cpp.
References GetCellCellstream(), GetCellType(), and IsValidCellIdx().
GetCell3dFacePoints() [1/2]
VecInt xms::XmUGridImpl::GetCell3dFacePoints (const int a_cellIdx, const int a_faceIdx) const override virtual
Get the cell face for given cell and face index.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
Returns
a vector of point indices for the face index of the cell
Implements xms::XmUGrid.
Definition at line 2088 of file XmUGrid.cpp.
Referenced by GetCell3dFaceAdjacentCell(), GetCell3dFaceAdjacentCellNoCache(), GetCell3dFacesPoints(), GetCellXySegments(), and GetFaceXySegments().
GetCell3dFacePoints() [2/2]
void xms::XmUGridImpl::GetCell3dFacePoints (const int a_cellIdx, const int a_faceIdx, VecInt & a_facePtIdxs) const override virtual
Get the cell face for given cell and face index.
Parameters
[in] a_cellIdx the index of the cell
[in] a_faceIdx the face index of the cell
[out] a_facePtIdxs a vector of point indices for the face
Implements xms::XmUGrid.
Definition at line 2100 of file XmUGrid.cpp.
References GetCellCellstream().
GetCell3dFacesPoints()
VecInt2d xms::XmUGridImpl::GetCell3dFacesPoints (const int a_cellIdx) const override virtual
Get the faces of a cell.
Parameters
[in] a_cellIdx the cells to whom the faces belong
Returns
a vector of faces, which is a vector of point indices
Implements xms::XmUGrid.
Definition at line 2160 of file XmUGrid.cpp.
References GetCell3dFaceCount(), and GetCell3dFacePoints().
Referenced by IsCellValidWithPointChange().
GetCellAdjacentCells() [1/2]
VecInt xms::XmUGridImpl::GetCellAdjacentCells (const int a_cellIdx) const override virtual
Get the cells neighboring a cell (cells associated with any of it's points)
Parameters
[in] a_cellIdx the index of the cell
Returns
vector of cell indices
Implements xms::XmUGrid.
Definition at line 1518 of file XmUGrid.cpp.
Referenced by GetCellEdgeAdjacentCells().
GetCellAdjacentCells() [2/2]
void xms::XmUGridImpl::GetCellAdjacentCells (const int a_cellIdx, VecInt & a_cellNeighbors) const override virtual
Get the cells neighboring a cell (cells associated with any of it's points)
Parameters
[in] a_cellIdx the index of the cell
[out] a_cellNeighbors vector of cell indices
Implements xms::XmUGrid.
Definition at line 1529 of file XmUGrid.cpp.
References GetCellPoints(), and GetPointAdjacentCells().
GetCellCellstream() [1/2]
bool xms::XmUGridImpl::GetCellCellstream (const int a_cellIdx, VecInt & a_cellstream) const override virtual
Get cell stream vector for a single cell.
Parameters
[in] a_cellIdx the index of the cell
[in] a_cellstream The cellstream of the cell
See also
SetCellstream for more detail on cell stream definitions.
Returns
whether it was successfull or not
Implements xms::XmUGrid.
Definition at line 1501 of file XmUGrid.cpp.
References m_cellIdxToStreamIdx, and m_cellstream.
Referenced by GetCell3dFacePointCount(), GetCell3dFacePoints(), GetCellEdge(), GetCellPointCount(), GetCellPoints(), and GetNumberOfPolyhedronEdges().
GetCellCellstream() [2/2]
void xms::XmUGridImpl::GetCellCellstream (const int a_cellIdx, const int ** a_start, int & a_length) const private
Internal function to get start of cell stream for an individual cell. Returns nullptr and zero length for invalid cell index.
Parameters
[in] a_cellIdx the index of the cell
[out] a_start pointer to the start of the stream for the cell
[out] a_length the length of the stream for the cell
Definition at line 2604 of file XmUGrid.cpp.
References GetCellType(), m_cellIdxToStreamIdx, and m_cellstream.
GetCellCentroid()
bool xms::XmUGridImpl::GetCellCentroid (int a_cellIdx, Pt3d & a_centroid) const override virtual
Get the centroid location of a cell.
Parameters
[in] a_cellIdx The index of the cell.
[out] a_centroid The location of the cell centroid.
Returns
False if the cell index does not exist.
Implements xms::XmUGrid.
Definition at line 1584 of file XmUGrid.cpp.
References GetCellLocations(), GetCellPlanViewPolygon(), and IsValidCellIdx().
GetCellCount()
int xms::XmUGridImpl::GetCellCount () const override virtual
Get the number of cells.
Returns
the number of cells
Implements xms::XmUGrid.
Definition at line 1283 of file XmUGrid.cpp.
References m_cellIdxToStreamIdx.
Referenced by CalculateCacheValues(), GetDimensionCounts(), and IsValidCellIdx().
GetCellDimension()
int xms::XmUGridImpl::GetCellDimension (const int a_cellIdx) const override virtual
Get the dimension of the specified cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
the dimension of the cells or -1 if invalid index or invalid dimension
Implements xms::XmUGrid.
Definition at line 1440 of file XmUGrid.cpp.
References DimensionFromCellType(), and GetCellType().
Referenced by GetCellPlanViewPolygon(), GetDimensionCounts(), and IsCellValidWithPointChange().
GetCellEdge()
XmEdge xms::XmUGridImpl::GetCellEdge (const int a_cellIdx, const int a_edgeIdx) const override virtual
Get the points of a cell.
Parameters
[in] a_cellIdx the index of the cell
[in] a_edgeIdx the index of the edge
Returns
a standard pair of point indices (which is an edge)
Implements xms::XmUGrid.
Definition at line 1788 of file XmUGrid.cpp.
References GetCellCellstream(), xms::XmEdge::GetFirst(), xms::XmEdge::GetSecond(), and GetUniqueEdgesFromPolyhedronCellstream().
Referenced by GetCellEdgeAdjacentCells(), GetCellEdges(), and GetPointAdjacentPoints().
GetCellEdgeAdjacentCells() [1/2]
VecInt xms::XmUGridImpl::GetCellEdgeAdjacentCells (const int a_cellIdx, const int a_edgeIdx) const override virtual
Get the index of the adjacent cells (that shares the same cell edge)
Parameters
[in] a_cellIdx the index of the cell
[in] a_edgeIdx the index of the edge
Returns
a vector of cell indices of the adjacent cells
Implements xms::XmUGrid.
Definition at line 1851 of file XmUGrid.cpp.
Referenced by GetCell2dEdgeAdjacentCell().
GetCellEdgeAdjacentCells() [2/2]
void xms::XmUGridImpl::GetCellEdgeAdjacentCells (const int a_cellIdx, const int a_edgeIdx, VecInt & a_adjacentCellIdxs) const override virtual
Get the index of the adjacent cells (that shares the same cell edge)
Parameters
[in] a_cellIdx the index of the cell
[in] a_edgeIdx the index of the edge
[out] a_adjacentCellIdxs a vector of cell indices of the adjacent cells
Implements xms::XmUGrid.
Definition at line 1864 of file XmUGrid.cpp.
References GetCellAdjacentCells(), GetCellEdge(), GetCellEdgeCount(), and xms::XmEdge::IsEquivalent().
GetCellEdgeCount()
int xms::XmUGridImpl::GetCellEdgeCount (const int a_cellIdx) const override virtual
Get the number of edges for a cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
the count of cell edges
Implements xms::XmUGrid.
Definition at line 1748 of file XmUGrid.cpp.
References GetCellType(), GetNumberOfItemsForCell(), GetNumberOfPolyhedronEdges(), and XM_ASSERT.
Referenced by GetCellEdgeAdjacentCells(), GetCellEdges(), and GetPointAdjacentPoints().
GetCellEdges() [1/2]
std::vector< XmEdge > xms::XmUGridImpl::GetCellEdges (const int a_cellIdx) const override virtual
Get the Edges of a cell.
Parameters
[in] a_cellIdx the cells to whom the edges belong
Returns
a vector of edges
Implements xms::XmUGrid.
Definition at line 1943 of file XmUGrid.cpp.
Referenced by IsCellValidWithPointChange().
GetCellEdges() [2/2]
void xms::XmUGridImpl::GetCellEdges (const int a_cellIdx, std::vector< XmEdge > & a_edges) const override virtual
Get the Edges of a cell.
Parameters
[in] a_cellIdx the cells to whom the edges belong
[out] a_edges a vector of edges (organized in std::pairs)
Implements xms::XmUGrid.
Definition at line 1954 of file XmUGrid.cpp.
References GetCellEdge(), and GetCellEdgeCount().
GetCellExtents()
void xms::XmUGridImpl::GetCellExtents (const int a_cellIdx, Pt3d & a_min, Pt3d & a_max) const override virtual
Get the extents of the given cell.
Parameters
[in] a_cellIdx The cell index to get the extents of.
[out] a_min The minimum location.
[out] a_max The maximum location.
Implements xms::XmUGrid.
Definition at line 1451 of file XmUGrid.cpp.
References GetCellLocations(), and GetExtentsFromPoints().
GetCellLocations()
void xms::XmUGridImpl::GetCellLocations (const int a_cellIdx, VecPt3d & a_cellLocations) const override virtual
Get locations of cell points.
Parameters
[in] a_cellIdx the index of the cell
[out] a_cellLocations The locations of the cell points
Implements xms::XmUGrid.
Definition at line 1377 of file XmUGrid.cpp.
References GetCellPoints(), and GetPointsLocations().
Referenced by GetCellCentroid(), GetCellExtents(), and GetPlanViewPolygon2d().
GetCellPlanViewPolygon()
bool xms::XmUGridImpl::GetCellPlanViewPolygon (int a_cellIdx, VecPt3d & a_polygon) const override virtual
Get a plan view polygon of a specified cell.
Parameters
[in] a_cellIdx The index of the cell.
[out] a_polygon Vector of Pt3d that is the plan view polygon.
Returns
False if the cell index does not exist or if the cell is not 2 or 3 dimensional.
Implements xms::XmUGrid.
Definition at line 1564 of file XmUGrid.cpp.
References GetCellDimension(), GetPlanViewPolygon2d(), GetPlanViewPolygon3d(), and IsValidCellIdx().
Referenced by GetCellCentroid().
GetCellPointCount()
int xms::XmUGridImpl::GetCellPointCount (const int a_cellIdx) const override virtual
Get the number of cell points (including polyhedron).
Parameters
[in] a_cellIdx the index of the cell
Returns
a vector of point indices
Implements xms::XmUGrid.
Definition at line 1295 of file XmUGrid.cpp.
References GetCellCellstream(), GetCellType(), and GetNumberOfItemsForCell().
GetCellPoints() [1/2]
VecInt xms::XmUGridImpl::GetCellPoints (const int a_cellIdx) const override virtual
Get the points of a cell (including polyhedron)
Parameters
[in] a_cellIdx the index of the cell
Returns
a vector of point indices
Implements xms::XmUGrid.
Definition at line 1332 of file XmUGrid.cpp.
Referenced by GetCellAdjacentCells(), GetCellLocations(), and GetPlanViewPolygon3d().
GetCellPoints() [2/2]
bool xms::XmUGridImpl::GetCellPoints (const int a_cellIdx, VecInt & a_cellPoints) const override virtual
Get the points of a cell.
Parameters
[in] a_cellIdx the index of the cell
[out] a_cellPoints the points of the cell
Returns
if the cell index is valid
Implements xms::XmUGrid.
Definition at line 1344 of file XmUGrid.cpp.
References GetCellCellstream(), GetUniquePointsFromPolyhedronSingleCellstream(), and XM_ENSURE_TRUE_NO_ASSERT.
GetCellstream()
const VecInt & xms::XmUGridImpl::GetCellstream () const override virtual
Get cell stream vector for the entire UGrid.
Returns
constant reference to the cell stream vector
Implements xms::XmUGrid.
Definition at line 1462 of file XmUGrid.cpp.
References m_cellstream.
GetCellType()
XmUGridCellType xms::XmUGridImpl::GetCellType (const int a_cellIdx) const override virtual
Get the cell type of a specified cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
The type of the specified cell or -1 if invalid.
Implements xms::XmUGrid.
Definition at line 1388 of file XmUGrid.cpp.
References m_cellIdxToStreamIdx, and m_cellstream.
Referenced by GetCell3dFaceCountNoCache(), GetCell3dFacePointCount(), GetCellCellstream(), GetCellDimension(), GetCellEdgeCount(), GetCellPointCount(), and GetNumberOfItemsForCell().
GetCellXySegments()
bool xms::XmUGridImpl::GetCellXySegments (int a_cellIdx, VecPt3d & a_segments) const private
Get the XY segments of a cell.
Parameters
[in] a_cellIdx the index of the cell
[out] a_segments The XY segments of a cell
Returns
whether the collected segments form a valid polygon
Definition at line 2828 of file XmUGrid.cpp.
References GetCell3dFaceCount(), GetCell3dFacePoints(), GetFaceXySegments(), and IsFaceSide().
Referenced by GetPlanViewPolygon3d().
GetDimensionCounts()
std::vector< int > xms::XmUGridImpl::GetDimensionCounts () const override virtual
Count all number of the cells with each dimension (0, 1, 2, 3)
Returns
the count of dimensions of all of the cells of the ugrid
Implements xms::XmUGrid.
Definition at line 1411 of file XmUGrid.cpp.
References GetCellCount(), GetCellDimension(), and m_cellDimensionCounts.
GetEdgeAdjacentCells() [1/2]
void xms::XmUGridImpl::GetEdgeAdjacentCells (const XmEdge & a_edge, VecInt & a_adjacentCellIdxs) const override virtual
Get the indices of the adjacent cells (that shares the same cell edge)
Parameters
[in] a_edge the edge (a pair of point indices)
[out] a_adjacentCellIdxs a vector of cell indices of the adjacent cells
Implements xms::XmUGrid.
Definition at line 1922 of file XmUGrid.cpp.
References xms::XmEdge::GetFirst(), GetPointsAdjacentCells(), and xms::XmEdge::GetSecond().
Referenced by GetEdgeAdjacentCells().
GetEdgeAdjacentCells() [2/2]
VecInt xms::XmUGridImpl::GetEdgeAdjacentCells (const XmEdge & a_edge) const override virtual
Get the index of the adjacent cells (that shares the same cell edge)
Parameters
[in] a_edge the edge (a pair of point indices)
Returns
a vector of cell indices of the adjacent cells
Implements xms::XmUGrid.
Definition at line 1932 of file XmUGrid.cpp.
References GetEdgeAdjacentCells().
GetEdgesOfFace()
void xms::XmUGridImpl::GetEdgesOfFace (const VecInt & a_face, std::vector< XmEdge > & a_edges) const private
Get the edges of a cell given a face.
Parameters
[in] a_face a vector of point indices of a face
[out] a_edges a vector of point indices of an edge
Definition at line 1690 of file XmUGrid.cpp.
Referenced by IsCellValidWithPointChange().
GetExtents()
void xms::XmUGridImpl::GetExtents (Pt3d & a_min, Pt3d & a_max) const override virtual
Get extents of all points in UGrid.
Parameters
[out] a_min minimum extent of all points
[out] a_max maximum extent of all points
Implements xms::XmUGrid.
Definition at line 1169 of file XmUGrid.cpp.
References GetExtentsFromPoints(), and m_points.
GetExtentsFromPoints()
void xms::XmUGridImpl::GetExtentsFromPoints (const VecPt3d & a_points, Pt3d & a_min, Pt3d & a_max) const private
Function to get the extents from a list of points. Will be removed after geometry library is built.
Parameters
[in] a_points The point locations to get the extents of.
[out] a_min Minimum point location.
[out] a_max Maximum point location.
Definition at line 2853 of file XmUGrid.cpp.
References xms::Pt3< T >::x, xms::Pt3< T >::y, and xms::Pt3< T >::z.
Referenced by GetCellExtents(), and GetExtents().
GetFaceXySegments()
bool xms::XmUGridImpl::GetFaceXySegments (int a_cellIdx, int a_faceIdx, VecPt3d & a_segments) const private
Get the Xy locations of Face Points.
Parameters
[in] a_cellIdx The index of the cells whose face points are wanted.
[in] a_faceIdx The index of the face whose points are wanted.
[out] a_segments The points of the face segments
Returns
true if successful.
Definition at line 2876 of file XmUGrid.cpp.
References GetCell3dFacePoints().
Referenced by GetCellXySegments().
GetLocations()
const VecPt3d & xms::XmUGridImpl::GetLocations () const override virtual
Get vector of UGrid points.
Returns
constant reference to vector of points
Implements xms::XmUGrid.
Definition at line 1096 of file XmUGrid.cpp.
References m_points.
GetModified()
bool xms::XmUGridImpl::GetModified () const override virtual
Returns the modified flag. Gets set when points or cells get changed.
Returns
the modified flag
Implements xms::XmUGrid.
Definition at line 1056 of file XmUGrid.cpp.
References m_modified.
GetNumberOfItemsForCell()
int xms::XmUGridImpl::GetNumberOfItemsForCell (const int a_cellIdx) const private
Get number of items given cell. For polyhedron number of items is number of faces. For other cell types it is number of points.
Parameters
[in] a_cellIdx the index of the cell
Returns
the number of faces for polyhedron or number of points.
Definition at line 2578 of file XmUGrid.cpp.
References GetCellType(), m_cellIdxToStreamIdx, and m_cellstream.
Referenced by GetCell3dFaceCountNoCache(), GetCellEdgeCount(), and GetCellPointCount().
GetNumberOfPolyhedronEdges()
int xms::XmUGridImpl::GetNumberOfPolyhedronEdges (const int a_cellIdx) const private
Get the number of edges for a polyhedron cell.
Parameters
[in] a_cellIdx the index of the cell
Returns
the number of edges
Definition at line 2625 of file XmUGrid.cpp.
References GetCellCellstream(), and GetUniqueEdgesFromPolyhedronCellstream().
Referenced by GetCellEdgeCount().
GetPlanViewPolygon2d()
bool xms::XmUGridImpl::GetPlanViewPolygon2d (int a_cellIdx, VecPt3d & a_polygon) const private
Get a plan view polygon of a specified 2D cell.
Parameters
[in] a_cellIdx the index of the cell
[out] a_polygon vector of Pt3d that is the plan view polygon
Returns
whether the operation was successful
Definition at line 2759 of file XmUGrid.cpp.
References GetCellLocations().
Referenced by GetCellPlanViewPolygon().
GetPlanViewPolygon3d()
bool xms::XmUGridImpl::GetPlanViewPolygon3d (int a_cellIdx, VecPt3d & a_polygon) const private
Get a plan view polygon of a specified 3D cell.
Parameters
[in] a_cellIdx the index of the cell
[out] a_polygon vector of Pt3d that is the plan view polygon
Returns
whether the operation was successful
Definition at line 2774 of file XmUGrid.cpp.
References xms::ConvexHull(), GetCellPoints(), GetCellXySegments(), and GetPointLocation().
Referenced by GetCellPlanViewPolygon().
GetPointAdjacentCells() [1/2]
VecInt xms::XmUGridImpl::GetPointAdjacentCells (const int a_pointIdx) const override virtual
Get the cells that are associated with the specified point.
Parameters
[in] a_pointIdx the index of the point
Returns
a vector of the cell indices associated with this point
Implements xms::XmUGrid.
Definition at line 1179 of file XmUGrid.cpp.
Referenced by GetCellAdjacentCells(), GetPointAdjacentPoints(), GetPointsAdjacentCells(), and IsValidPointChange().
GetPointAdjacentCells() [2/2]
void xms::XmUGridImpl::GetPointAdjacentCells (const int a_pointIdx, VecInt & a_adjacentCells) const override virtual
Get the cells that are associated with the specified point.
Parameters
[in] a_pointIdx the index of the point
[out] a_adjacentCells a vector of the adjacent cell indices
Returns
a vector of the cell indices associated with this point
Implements xms::XmUGrid.
Definition at line 1191 of file XmUGrid.cpp.
References m_pointIdxToPointsToCells, m_points, and m_pointsToCells.
GetPointAdjacentLocations()
void xms::XmUGridImpl::GetPointAdjacentLocations (int a_pointIdx, VecPt3d & a_edgePoints) const override virtual
Given a point gets point locations attached to the point by an edge.
Parameters
[in] a_pointIdx The point to get attached point from.
[out] a_edgePoints A vector of points attached across edges.
Implements xms::XmUGrid.
Definition at line 2002 of file XmUGrid.cpp.
References GetPointAdjacentPoints(), and GetPointsLocations().
GetPointAdjacentPoints()
void xms::XmUGridImpl::GetPointAdjacentPoints (int a_pointIdx, VecInt & a_edgePoints) const override virtual
Given a point gets point indices attached to the point by an edge.
Parameters
[in] a_pointIdx The point to get adjacent points from.
[out] a_edgePoints The indices of the adjacent points.
Implements xms::XmUGrid.
Definition at line 1969 of file XmUGrid.cpp.
References GetCellEdge(), GetCellEdgeCount(), xms::XmEdge::GetFirst(), GetPointAdjacentCells(), and xms::XmEdge::GetSecond().
Referenced by GetPointAdjacentLocations().
GetPointCount()
int xms::XmUGridImpl::GetPointCount () const override virtual
Get the number of points.
Returns
the number of points
Implements xms::XmUGrid.
Definition at line 1088 of file XmUGrid.cpp.
References m_points.
GetPointLocation()
Pt3d xms::XmUGridImpl::GetPointLocation (const int a_pointIdx) const override virtual
Get the point.
Parameters
[in] a_pointIdx the index of the point
Returns
the point or an initialize point if the index is invalid
Implements xms::XmUGrid.
Definition at line 1114 of file XmUGrid.cpp.
References m_points.
Referenced by DoEdgesCrossWithPointChange(), GetPlanViewPolygon3d(), GetPointsLocations(), GetPointXy0(), and IsFaceSide().
GetPointsAdjacentCells() [1/4]
VecInt xms::XmUGridImpl::GetPointsAdjacentCells (const VecInt & a_points) const override virtual
Gets the common cells from a vector of points.
Parameters
[in] a_points a vector of unique points
Returns
a vector of cell indices
Implements xms::XmUGrid.
Definition at line 1207 of file XmUGrid.cpp.
Referenced by GetCell3dFaceAdjacentCellNoCache(), GetEdgeAdjacentCells(), and GetPointsAdjacentCells().
GetPointsAdjacentCells() [2/4]
void xms::XmUGridImpl::GetPointsAdjacentCells (const int * a_pointIdxs, int a_numPointIdxs, VecInt & a_commonCellIdxs) const virtual
Gets the common cells from a vector of points.
Parameters
[in] a_pointIdxs an array of point indices
[in] a_numPointIdxs number of points in array
[out] a_commonCellIdxs a vector of cell indices
Definition at line 1220 of file XmUGrid.cpp.
References GetPointAdjacentCells().
GetPointsAdjacentCells() [3/4]
void xms::XmUGridImpl::GetPointsAdjacentCells (const VecInt & a_pointIdxs, VecInt & a_adjacentCellIdxs) const override virtual
Gets the cells adjacent to all of a vector of points.
Parameters
[in] a_pointIdxs a vector of unique points
[out] a_adjacentCellIdxs a vector of cell indices
Implements xms::XmUGrid.
Definition at line 1259 of file XmUGrid.cpp.
References GetPointsAdjacentCells().
GetPointsAdjacentCells() [4/4]
void xms::XmUGridImpl::GetPointsAdjacentCells (const int a_pointIdx1, const int a_pointIdx2, VecInt & a_adjacentCellIdxs) const override virtual
Gets the cells adjacent to both of the two points.
Parameters
[in] a_pointIdx1 first point index
[in] a_pointIdx2 second point index
[out] a_adjacentCellIdxs a vector of cell indices
Implements xms::XmUGrid.
Definition at line 1271 of file XmUGrid.cpp.
References GetPointsAdjacentCells().
GetPointsLocations()
VecPt3d xms::XmUGridImpl::GetPointsLocations (const VecInt & a_points) const override virtual
Convert a vector of point indices into a vector of point 3d.
Parameters
[in] a_points a vector of point indices
Returns
vector of point 3d
Implements xms::XmUGrid.
Definition at line 1154 of file XmUGrid.cpp.
References GetPointLocation().
Referenced by GetCellLocations(), and GetPointAdjacentLocations().
GetPointXy0()
Pt3d xms::XmUGridImpl::GetPointXy0 (const int a_pointIdx) const override virtual
Get the X, Y location of a point.
Parameters
[in] a_pointIdx The index of the point.
Returns
The location of the point with Z set to 0.0.
Implements xms::XmUGrid.
Definition at line 1142 of file XmUGrid.cpp.
References GetPointLocation(), and xms::Pt3< T >::z.
GetUniqueEdgesFromPolyhedronCellstream()
void xms::XmUGridImpl::GetUniqueEdgesFromPolyhedronCellstream (const int * a_start, int & a_length, boost::container::flat_set< XmEdge > & a_cellEdges, int & a_currIdx) static private
Get the unique edges in a flat set for a given polyhedron.
Parameters
[in] a_start the UGrid cell stream (integer pointer)
[in] a_length the length of the cell stream
[in] a_cellEdges Unique cell edges of the polyhedron
[in] a_currIdx the index of the cell stream; this should reference the number of points in the first face. This variable will be updated to the cell type of the next cell.
Note
: This function does NOT verify cellstream size!! This function needs to be efficient!
Definition at line 2726 of file XmUGrid.cpp.
Referenced by GetCellEdge(), and GetNumberOfPolyhedronEdges().
GetUniquePointsFromPolyhedronCellstream()
void xms::XmUGridImpl::GetUniquePointsFromPolyhedronCellstream (const VecInt & a_cellstream, const int a_numCellItems, int & a_currIdx, VecInt & a_uniqueGetCellPoints, VecInt & a_cellMask) static private
Get the unique points in a flat set.
Parameters
[in] a_cellstream the UGrid cell stream
[in] a_numCellItems the number of cell faces in the polyhedron
[in] a_currIdx the index of the cell stream; this should reference the number of points in the first face. This variable will be updated to the cell type of the next cell.
[out] a_uniqueGetCellPoints the unique points of the polyhedron
[out] a_cellMask a list of integers representing the last time a point was found
Note
: This function does NOT verify cellstream size!! This function needs to be efficient!
Definition at line 2654 of file XmUGrid.cpp.
Referenced by UpdatePointLinks().
GetUniquePointsFromPolyhedronSingleCellstream()
bool xms::XmUGridImpl::GetUniquePointsFromPolyhedronSingleCellstream (const VecInt & a_cellstream, VecInt & a_cellPoints) static private
Get the unique points for cell stream of a single polyhedron cell.
Parameters
[in] a_cellstream a single cell stream that is a polyhedron type
[out] a_cellPoints the points of the cell
Returns
false if invalid stream
Definition at line 2683 of file XmUGrid.cpp.
Referenced by GetCellPoints().
IsCellValidWithPointChange()
bool xms::XmUGridImpl::IsCellValidWithPointChange (const int a_cellIdx, const int a_changedPtIdx, const Pt3d & a_newPosition) const private
Determine whether a cell is valid after a point is moved.
Parameters
[in] a_cellIdx the index of the cell
[in] a_changedPtIdx index of the point to be changed
[in] a_newPosition location the point is to be moved to
Returns
whether the cell is valid
Definition at line 1617 of file XmUGrid.cpp.
References DoEdgesCrossWithPointChange(), GetCell3dFacesPoints(), GetCellDimension(), GetCellEdges(), and GetEdgesOfFace().
Referenced by IsValidPointChange().
IsFaceSide()
bool xms::XmUGridImpl::IsFaceSide (const VecInt & a_facePts) const private
Get whether the cell face is of a side orientation. Only works for plan view prismatic cells.
Parameters
[in] a_facePts the points in the face
Returns
whether the face is a Side
Definition at line 2804 of file XmUGrid.cpp.
References GetPointLocation(), xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by GetCellXySegments().
IsValidCellIdx()
bool xms::XmUGridImpl::IsValidCellIdx (const int a_cellIdx) const private
Determine if a cell index is valid.
Parameters
[in] a_cellIdx the index of the cell
Returns
True if the cell index is valid.
Definition at line 1657 of file XmUGrid.cpp.
References GetCellCount().
Referenced by GetCell3dFaceCount(), GetCell3dFaceCountNoCache(), GetCell3dFacePointCount(), GetCellCentroid(), and GetCellPlanViewPolygon().
IsValidPointChange()
bool xms::XmUGridImpl::IsValidPointChange (const int a_changedPtIdx, const Pt3d & a_newPosition) const override virtual
Determine whether adjacent cells are valid after a point is moved.
Parameters
[in] a_changedPtIdx index of the point to be changed
[in] a_newPosition location the point is to be moved to
Returns
whether the change is valid
Implements xms::XmUGrid.
Definition at line 1667 of file XmUGrid.cpp.
References GetPointAdjacentCells(), IsCellValidWithPointChange(), and m_points.
SetCellstream()
bool xms::XmUGridImpl::SetCellstream (const VecInt & a_cellstream) override virtual
Set the ugrid cells for the entire UGrid using a cell stream.
Parameters
[in] a_cellstream cells defined as follows: Hexahedrons, polygons, quads, triangles etc: Cell type (ElemTypeEnum), number of points, point numbers. Generally 0-based, CCW, bottom, then top. Not true for pixel or voxel. Polyhedrons: Cell type, number of faces, [num points in face, point numbers (0-based, CCW when looking in)] repeated for each face.
Returns
if successfully set
Implements xms::XmUGrid.
Definition at line 1479 of file XmUGrid.cpp.
References xmlog::error, xms::XmUGrid::IsValidCellstream(), m_cellstream, SetModified(), UpdateLinks(), and XM_LOG.
SetLocations()
void xms::XmUGridImpl::SetLocations (const VecPt3d & a_locations) override virtual
Set UGrid points.
Parameters
[in] a_locations vector of point locations
Implements xms::XmUGrid.
Definition at line 1104 of file XmUGrid.cpp.
References m_points, and SetModified().
SetPointLocation()
bool xms::XmUGridImpl::SetPointLocation (const int a_pointIdx, const Pt3d & a_location) override virtual
Set the point.
Parameters
[in] a_pointIdx the index of the point
[in] a_location The new location of the specified point
Returns
whether the point was successfully set
Implements xms::XmUGrid.
Definition at line 1126 of file XmUGrid.cpp.
References m_points, and SetModified().
SetUseCache()
void xms::XmUGridImpl::SetUseCache (bool a_useCache) override virtual
Turn on or off use of caching.
Parameters
a_useCache Flag to determine if caching will be used.
Implements xms::XmUGrid.
Definition at line 1079 of file XmUGrid.cpp.
References m_useCache.
Member Data Documentation
m_cellstream
VecInt xms::XmUGridImpl::m_cellstream private
UGrid cell stream.
See also
SetCellstream, GetCellstream
Definition at line 212 of file XmUGrid.cpp.
Referenced by GetCellCellstream(), GetCellstream(), GetCellType(), GetNumberOfItemsForCell(), SetCellstream(), UpdateCellLinks(), and UpdatePointLinks().
m_pointIdxToPointsToCells
VecInt xms::XmUGridImpl::m_pointIdxToPointsToCells private
Indexes for each point in array of points cells
Definition at line 216 of file XmUGrid.cpp.
Referenced by GetPointAdjacentCells(), and UpdatePointLinks().
m_pointsToCells
VecInt xms::XmUGridImpl::m_pointsToCells private
Array of points cells (goes from pointIdx to list of cells)
Definition at line 214 of file XmUGrid.cpp.
Referenced by GetPointAdjacentCells(), and UpdatePointLinks().
The documentation for this class was generated from the following file:
/home/conan/xmsgrid/ugrid/XmUGrid.cpp