xmsgrid: xms::XmEdge Class Reference
xms::XmEdge Class Reference
Two integer values representing an edge of an XmUGrid. By default has a direction. Can be sorted to have minimum index first.
Public Member Functions
XmEdge ()
Default constructor.
XmEdge (int a_pt1, int a_pt2, bool a_sorted=false)
Constructor.
XmEdge (const std::pair< int, int > &a_edge)
Constructor.
bool operator< (const XmEdge &a_rhs) const
Less than operator by first index then second.
bool operator== (const XmEdge &a_rhs) const
Equals operator.
int GetFirst () const
Get the first index.
void SetFirst (int a_pt1)
Set the first index.
int GetSecond () const
Get the second index.
void SetSecond (int a_pt2)
Set the second index.
bool IsEquivalent (const XmEdge &a_edge) const
Test if edge is the same ignoring direction.
void SortIndexes ()
Sort the indexes so minimum index is first.
Private Attributes
int m_pt1
First point on the edge.
int m_pt2
Second point on the edge.
Detailed Description
Two integer values representing an edge of an XmUGrid. By default has a direction. Can be sorted to have minimum index first.
Definition at line 33 of file XmEdge.h.
Constructor & Destructor Documentation
XmEdge() [1/2]
xms::XmEdge::XmEdge (int a_pt1, int a_pt2, bool a_sorted = false)
Constructor.
Parameters
[in] a_pt1 The first index.
[in] a_pt2 The second index.
[in] a_sorted If true set the first index to be the minimum index.
Definition at line 58 of file XmEdge.cpp.
References SortIndexes().
XmEdge() [2/2]
xms::XmEdge::XmEdge (const std::pair< int, int > & a_edge) explicit
Constructor.
Parameters
[in] a_edge The edge as an int pair.
Definition at line 69 of file XmEdge.cpp.
Member Function Documentation
GetFirst()
int xms::XmEdge::GetFirst () const
Get the first index.
Returns
The first index.
Definition at line 103 of file XmEdge.cpp.
References m_pt1.
Referenced by xms::XmUGrid::Impl::GetCell2dEdgeAdjacentCell(), xms::XmUGrid::Impl::GetCellEdge(), xms::XmUGrid::Impl::GetEdgeAdjacentCells(), and xms::XmUGrid::Impl::GetPointAdjacentPoints().
GetSecond()
int xms::XmEdge::GetSecond () const
Get the second index.
Returns
The second index.
Definition at line 119 of file XmEdge.cpp.
References m_pt2.
Referenced by xms::XmUGrid::Impl::GetCellEdge(), xms::XmUGrid::Impl::GetEdgeAdjacentCells(), and xms::XmUGrid::Impl::GetPointAdjacentPoints().
IsEquivalent()
bool xms::XmEdge::IsEquivalent (const XmEdge & a_edge) const
Test if edge is the same ignoring direction.
Parameters
a_edge The edge to compare against.
Returns
True if edges are same when indexes are in sorted order.
Definition at line 136 of file XmEdge.cpp.
References m_pt1, and m_pt2.
Referenced by xms::XmUGrid::Impl::GetCell2dEdgeAdjacentCell(), xms::XmUGrid::Impl::GetCellEdgeAdjacentCells(), XmEdgeUnitTests::testIsEquivalent(), and xms::XmEdgesEquivalent().
operator<()
bool xms::XmEdge::operator< (const XmEdge & a_rhs) const
Less than operator by first index then second.
Parameters
[in] a_rhs The edge to compare against.
Returns
true if this edge is less than a_rhs.
Definition at line 79 of file XmEdge.cpp.
References m_pt1, and m_pt2.
operator==()
bool xms::XmEdge::operator== (const XmEdge & a_rhs) const
Equals operator.
Parameters
[in] a_rhs The edge to compare against.
Returns
true if edges are equal.
Definition at line 95 of file XmEdge.cpp.
References m_pt1, and m_pt2.
SetFirst()
void xms::XmEdge::SetFirst (int a_pt1)
Set the first index.
Parameters
[in] a_pt1 The first index.
Definition at line 111 of file XmEdge.cpp.
References m_pt1.
SetSecond()
void xms::XmEdge::SetSecond (int a_pt2)
Set the second index.
Parameters
[in] a_pt2 The second index.
Definition at line 127 of file XmEdge.cpp.
References m_pt2.
The documentation for this class was generated from the following files:
/home/conan/xmsgrid/ugrid/XmEdge.h
/home/conan/xmsgrid/ugrid/XmEdge.cpp