xmsgrid: xms Namespace Reference
xms Namespace Reference
XMS Namespace.
Namespaces
Classes
struct BarycentricVals
Structure for Barycentric coordinate calculations.
class DaStreamReader
class DaStreamWriter
struct edgerecord
Defines an edge that intersects a breakline.
class ETestMessagingState
class fSatisfies
a class used with the boost::geometry::index::satisfies function
class GmExtents2d
2D geometric extents (min/max).
class GmExtents3d
3D geometric extents (min/max).
class GmMultiPolyIntersectionSorter
Base class for sorting intersections from GmMultiPolyIntersector.
class GmMultiPolyIntersectionSorterTerse
Class for sorting intersections from GmMultiPolyIntersector in a terse way (with no duplicate info).
class GmMultiPolyIntersector
See GmMultiPolyIntersectorImpl comments.
struct GmMultiPolyIntersectorData
Struct used by GmMultiPolyIntersector.
class GmMultiPolyIntersectorImpl
Used to intersect a line segment with any number of polygons in 2D. Returns the intersected polygons in order along with t values. May be an alternative to SurfaceIter and feiTraverseLineSegment2.
class GmPolygon
Interface to a boost::geometry::polygon class.
class GmPolygonImpl
Wraps a boost polygon for point in poly, min distance from point to poly etc.
class GmPolyLinePtRedistributer
Redistributes the point locations on a polyline based on a size.
class GmPolyLinePtRedistributerImpl
Implementation of GmPolyLinePtRedistributer.
class GmPtSearch
Spatial index for searching points.
class GmPtSearchImpl
Implementation of GmPtSearch. Generic class for searching location data. Uses a boost R-tree to query a set of locations. Works for 2D and 3D.
class GmTriSearch
Spatial index for searching triangles.
class GmTriSearchImpl
Implementation of GmTriSearch.
class idx_pt
class for indexing the points
class idx_tri
provides indexing for the spatial index
class ix
An intersection point of a line with a polygon.
class ltPt2
class ltPt3
class ltPt3_2D
class Observer
class Progress
class ProgressListener
class Pt2
class Pt3
class Pt4
class SharedSingleton
class Singleton
class StCommaNumpunct
class StTemp2DigitExponents
class TrAutoFixFourTrianglePts
class TrAutoFixFourTrianglePtsImpl
Used to delete points that are connected to 4 triangles and then retriangulate the void.
class TrBreaklineAdder
Adds breaklines to a tin.
class TrBreaklineAdderImpl
Adds breaklines to a triangulation.
class TrOuterTriangleDeleter
class TrOuterTriangleDeleterImpl
Used to delete tin triangles that are outside given polygons. The polygons may include holes - polygons inside polygons.
class TrTin
class TrTinImpl
Class to encapsulate a tin made simply of arrays of points, triangles and adjacency information. Also methods to manipulate it.
class TrTriangulator
Base class used to derive a class to triangulate points.
class TrTriangulatorPoints
Class to triangulate simple points.
class XmEdge
Two integer values representing an edge of an XmUGrid. By default has a direction. Can be sorted to have minimum index first.
class XmLog
class XmUGrid
Geometry for an unstructured grid. An XmUGrid is defined as a vector of 3d points and a stream of cells. Throughout this interface, we use these terms:
Typedefs
typedef boost::geometry::model::d2::point_xy< double > GmBstPt2d
Boost geometry 2d point.
typedef boost::geometry::model::polygon< GmBstPt2d > GmBstPoly2d
Boost polygon 2d.
typedef boost::geometry::model::polygon< Pt3d > GmBstPoly3d
Boost polygon 3d.
typedef boost::geometry::model::box< Pt3d > GmBstBox3d
Boost box 3d.
typedef boost::geometry::model::linestring< Pt3d > GmBstLine3d
Boost line 3d.
typedef boost::geometry::ring_type< GmBstPoly3d >::type GmBstRing3d
Boost ring 3d.
typedef std::pair< GmBstBox3d, int > ValueBox
Pair used in rtree.
typedef bgi::rtree< ValueBox, bgi::quadratic< 8 > > RtreeBox
Rtree typedef.
typedef bg::model::box< bPt > box
box
typedef size_t value
value
typedef bgi::quadratic< 8 > qRtree
qRtree
typedef std::vector< edgerecord > VecEdge
Vector of edgerecord.
Enumerations
enum Turn_enum { TURN_LEFT, TURN_RIGHT, TURN_COLINEAR_180, TURN_COLINEAR_0 }
direction of turn between 3 points
enum PtInOutOrOn_enum { PT_ERROR = -1, PT_IN, PT_OUT, PT_ON }
point in, out, or on
enum GmMultiPolyIntersectorQueryEnum { GMMPIQ_COVEREDBY, GMMPIQ_INTERSECTS }
Type of query.
enum XmUGridCellType {
XMU_INVALID_CELL_TYPE = -1, XMU_EMPTY_CELL = 0, XMU_VERTEX = 1, XMU_POLY_VERTEX = 2,
XMU_LINE = 3, XMU_POLY_LINE = 4, XMU_TRIANGLE = 5, XMU_TRIANGLE_STRIP = 6,
XMU_POLYGON = 7, XMU_PIXEL = 8, XMU_QUAD = 9, XMU_TETRA = 10,
XMU_VOXEL = 11, XMU_HEXAHEDRON = 12, XMU_WEDGE = 13, XMU_PYRAMID = 14,
XMU_PENTAGONAL_PRISM = 15, XMU_HEXAGONAL_PRISM = 16, XMU_QUADRATIC_EDGE = 21, XMU_QUADRATIC_TRIANGLE = 22,
XMU_QUADRATIC_QUAD = 23, XMU_QUADRATIC_POLYGON = 36, XMU_QUADRATIC_TETRA = 24, XMU_QUADRATIC_HEXAHEDRON = 25,
XMU_QUADRATIC_WEDGE = 26, XMU_QUADRATIC_PYRAMID = 27, XMU_BIQUADRATIC_QUAD = 28, XMU_TRIQUADRATIC_HEXAHEDRON = 29,
XMU_QUADRATIC_LINEAR_QUAD = 30, XMU_QUADRATIC_LINEAR_WEDGE = 31, XMU_BIQUADRATIC_QUADRATIC_WEDGE = 32, XMU_BIQUADRATIC_QUADRATIC_HEXAHEDRON = 33,
XMU_BIQUADRATIC_TRIANGLE = 34, XMU_CUBIC_LINE = 35, XMU_CONVEX_POINT_SET = 41, XMU_POLYHEDRON = 42,
XMU_PARAMETRIC_CURVE = 51, XMU_PARAMETRIC_SURFACE = 52, XMU_PARAMETRIC_TRI_SURFACE = 53, XMU_PARAMETRIC_QUAD_SURFACE = 54,
XMU_PARAMETRIC_TETRA_REGION = 55, XMU_PARAMETRIC_HEX_REGION = 56, XMU_HIGHER_ORDER_EDGE = 60, XMU_HIGHER_ORDER_TRIANGLE = 61,
XMU_HIGHER_ORDER_QUAD = 62, XMU_HIGHER_ORDER_POLYGON = 63, XMU_HIGHER_ORDER_TETRAHEDRON = 64, XMU_HIGHER_ORDER_WEDGE = 65,
XMU_HIGHER_ORDER_PYRAMID = 66, XMU_HIGHER_ORDER_HEXAHEDRON = 67, XMU_NUMBER_OF_CELL_TYPES
}
Matches cell types from VTK (see vtkCellType.h)
enum XmUGridFaceOrientation {
XMU_ORIENTATION_UNKNOWN = -1, XMU_ORIENTATION_SIDE = 0, XMU_ORIENTATION_TOP = 1, XMU_ORIENTATION_BOTTOM = 2,
XMU_ORIENTATION_NUMBER
}
The orientation of a 3D face must be one of these.
Functions
bool gmPointInOrOnBox2d (const Pt3d &a_bMin, const Pt3d &a_bMax, const Pt3d &a_pt)
finds if a point is in or on a box in 2d
bool gmBoxesOverlap2d (const Pt3d &a_b1Min, const Pt3d &a_b1Max, const Pt3d &a_b2Min, const Pt3d &a_b2Max)
finds if 2 boxes overlap in 2d
void gmCalculateNormalizedPlaneCoefficients (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3, double *a, double *b, double *c, double *d)
Calculates the plane coefficients for a triangle. Given point references calculate coefficents for plane (ax+by+cz+d=0).
void gmCalculateNormalizedPlaneCoefficients (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, double *a, double *b, double *c, double *d)
Calculates the plane coefficients for a triangle. Given point pointers calculate coefficents for plane (ax+by+cz+d=0).
double gmMiddleZ (const VecPt3d &a_points)
Returns the z value halfway between the max and min z. Different from the average z (where many points can skew the average).
PtInOutOrOn_enum gmPtInCircumcircle (const Pt3d &pt, Pt3d circumcirclePts[3])
Is a given point inside a circumcircle defined by three points?
double gmXyDistanceSquared (const Pt3d &pt1, const Pt3d &pt2)
Calculate XY distance between two 3D points.
bool gmCircumcircleWithTol (const Pt3d *pt1, const Pt3d *pt2, const Pt3d *pt3, double *xc, double *yc, double *r2, double tol)
Computes center & radius squared for circumcircle of triangle made by the three points.
int gmCartToBary (const Pt3d *cart, const Pt3d *orig, double coef[6], int dir, Pt3d *bary)
Compute Barycentric coords for point. Use gmBaryPrepare to get the coefficients and direction.
int gmBaryPrepare (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, const Pt3d *norm, Pt3d *orig, double coef[6], int *dir, bool flag)
For a tri - compute dir & coefs to compute Barycentric coords.
bool gmColinearWithTol (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3, const double tol)
Returns true if (the three vertices are gmColinear. Result should be insensitive to the order of the vertices.
bool gmIntersectLineSegmentsWithTol (const Pt3d &one1, const Pt3d &one2, const Pt3d &two1, const Pt3d &two2, double *xi, double *yi, double *zi1, double *zi2, double tol)
Intersects the plan projection of two line segments.
bool gmCounterClockwiseTri (const Pt3d &vtx0, const Pt3d &vtx1, const Pt3d &vtx2)
Returns true if the triangle is wrapped counter clockwise.
double gmCross2D (const double &dx1, const double &dy1, const double &dx2, const double &dy2)
Returns the cross product of two 2-d vectors.
double gmCross2D (const Pt3d &a_origin, const Pt3d &a_A, const Pt3d &a_B)
2D cross product of two points
double gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
double gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn, double a_magn, double a_magp)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
double gmAngleBetweenEdges (const Pt3d &p1, const Pt3d &p2, const Pt3d &p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
double gmAngleBetweenEdges (const Pt2d &p1, const Pt2d &p2, const Pt2d &p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
double gmComputeDeviationInDirection (const Pt3d &a_p0, const Pt3d &a_p1, const Pt3d &a_p2)
Computes the deviation in direction from one seg to next seg 1 is from a_p0 to a_p1 seg 2 is from a_p1 to a_p2.
bool gmOnLineWithTol (const Pt3d &p1, const Pt3d &p2, const double x, const double y, const double tol)
Determines if a point (x,y) is on the line defined by p1 and p2. Assumes p1 and p2 aren't the same.
bool gmOnLineAndBetweenEndpointsWithTol (const Pt3d &a_pt1, const Pt3d &a_pt2, const double a_x, const double a_y, double a_tol)
determines if (x,y) is on the line passing through p1 & p2 and between p1 & p2.
void gmAddToExtents (const Pt3d &a_pt, Pt3d &a_min, Pt3d &a_max)
Compares a_pt to a_min and a_max. If a_pt is less than a_min or greater than a_max, a_min and a_max are updated.
void gmAddToExtents (const Pt3d &a_pt, Pt2d &a_min, Pt2d &a_max)
void gmAddToExtents (const Pt2d &a_pt, Pt3d &a_min, Pt3d &a_max)
double gmXyDistance (double x1, double y1, double x2, double y2)
Compute the 2d distance between 2 points.
double gmXyDistance (const Pt3d &pt1, const Pt3d &pt2)
Turn_enum gmTurn (const Pt3d &a_v1, const Pt3d &a_v2, const Pt3d &a_v3, double a_angtol)
Determine if angle a_v1, a_v2, a_v3 is a left turn, a right turn, colinear 180 degrees, or colinear 0 degrees.
Pt3d gmComputeCentroid (const VecPt3d &a_points)
Computes the centroid of points (but not of a polygon). Shouldn't pass an empty vector (no checks are performed).
Pt3d gmComputePolygonCentroid (const VecPt3d &pts)
Computes the plan view centroid of a non-self-intersecting polygon.
bool gmLinesIntersect (const Pt3d &one1, const Pt3d &one2, const Pt3d &two1, const Pt3d &two2)
intersects the plan projection of two line segments (bad func name) segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
bool gmLinesCross (const Pt3d &a_segment1Point1, const Pt3d &a_segment1Point2, const Pt3d &a_segment2Point1, const Pt3d &a_segment2Point2)
Determine whether 2 line segments cross. The segments may touch at the end points.
template<typename T >
int gmPointInPolygon2D (const T *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
Determines whether (a_x, a_y) is inside=1, on=0, or outside=-1 the polygon defined by the given vertices.
int gmPointInPolygon2D (const Pt3d *a_verts, size_t a_num, double a_x, double a_y)
int gmPointInPolygon2D (const Pt3d *a_verts, size_t a_num, Pt3d a_pt)
int gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt2d a_pt)
int gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt3d a_pt)
int gmPointInPolygon2D (const Pt2i *a_verts, size_t a_num, Pt2i a_pt)
int gmPointInPolygon2D (const VecPt3d &a_verts, const Pt3d &a_pt)
template int gmPointInPolygon2D< Pt3d > (const Pt3d *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
template int gmPointInPolygon2D< Pt2d > (const Pt2d *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
template int gmPointInPolygon2D< Pt2i > (const Pt2i *a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
double gmComputeXyTol (const Pt3d &a_mn, const Pt3d &a_mx)
Given extents (min, max), compute a tolerance for the xy plane to be used with geometric functions.
double gmXyTol (bool a_set, double a_value)
Get or set (set first time) global xy tolerance for float operations.
double gmZTol (bool a_set, double a_value)
Get or set (set first time) global z tolerance for float operations.
bool gmEqualPointsXY (double x1, double y1, double x2, double y2, double tolerance)
Returns true if the points are equal to within gmXyTol().
bool gmEqualPointsXY (double x1, double y1, double x2, double y2)
bool gmEqualPointsXY (const Pt2d &a_pt1, const Pt2d &a_pt2, double tol)
bool gmEqualPointsXY (const Pt3d &a_pt1, const Pt3d &a_pt2, double tol)
bool gmEqualPointsXY (const Pt2i &point1, const Pt2i &point2)
bool gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2, double tolerance)
Returns true if the points are equal to within tolerance.
bool gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2)
bool gmEqualPointsXYZ (const Pt3d &pt1, const Pt3d &pt2, double tol)
bool gmPointInTriangleWithTol (const Pt3d *p1, const Pt3d *p2, const Pt3d *p3, double x, double y, double tol)
Returns true if (x,y) is in the tri formed by p1, p2, p3.
bool gmInsideOrOnLineWithTol (const Pt3d *p1, const Pt3d *p2, const Pt3d *inpoint, const double x, const double y, const double tol, double *dist)
Returns true if the (x,y) is on the line segment (p1,p2) or on the same side of the line as "inpoint". ASSERTs in debug if "inpoint" is on the line (within tol).
double gmPolygonArea (const Pt3d *pts, size_t npoints)
Compute 2d planview projection of area of polygon.
VecPt3d gmArrayToVecPt3d (double *a_array, int a_size)
Useful in testing to create a VecPt3d from a C array of xy pairs.
void gmEnvelopeOfPts (const VecPt3d &a_pts, Pt3d &a_min, Pt3d &a_max)
Calculates the envelope of a vector of points.
void gmOrderPointsCounterclockwise (const VecPt3d &a_pts, VecInt &a_ccwOrder, int a_startindex)
Orders array of points counter clockwise. Given non-empty array of points. array of point indices ordered counter clockwise based on the angle from the centroid where angle starts at point at startindex.
void gmOrderPointsCounterclockwise (VecPt3d &a_pts)
Overload to gmOrderPointsCounterclockwise.
double gmFindClosestPtOnSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt, Pt3d &a_newpt, const double a_tol)
Finds the closest point to another point on a segment.
double gmPtDistanceAlongSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt, const double a_tol)
Finds the distance along a segment for the location closest to a_pt.
bool gmInsideOfLineWithTol (const Pt3d &a_vertex1, const Pt3d &a_vertex2, const Pt3d &a_oppositevertex, const double a_x, const double a_y, const double a_tol)
Returns TRUE if the Point on the same side of the line (defined by vertex1 and vertex2) as oppositevertex.
void gmExtents2D (const VecPt3d &a_points, Pt2d &a_min, Pt2d &a_max)
Get the 2D extents of a vector of points.
void gmExtents2D (const VecPt3d &a_points, Pt3d &a_min, Pt3d &a_max)
void gmExtents3D (const VecPt3d &a_points, Pt3d &a_min, Pt3d &a_max)
Get the 3D extents of a vector of points.
double gmPerpendicularAngle (const Pt3d &a_pt1, const Pt3d &a_pt2)
Returns the angle in radians perpendicular to the two points.
double gmBisectingAngle (const Pt3d &a_p1, const Pt3d &a_p2, const Pt3d &a_p3)
Returns the angle (0-2pi) which bisects the edges p2-p1 and p2-p3 based on a ccw rotation from edge 1 to edge 2.
void gmComponentMagnitudes (double *a_x, double *a_y, double *a_mag, double *a_dir, bool a_tomagdir)
converts the magnitude and angle to xy components or vice versa
Pt3d gmCreateVector (const Pt3d &a_p1, const Pt3d &a_p2)
creates a vector from a_p1 to a_p2
double gmConvertAngleToBetween0And360 (double a_angle, bool a_InDegrees)
given an angle, this function will return the corresponding angle that matches it in the range of 0 deg to 360 deg
void gmCross3D (const Pt3d &a_vec1, const Pt3d &a_vec2, Pt3d *a_vec3)
Perform a cross product of Pt3d's.
double gmDot3D (const Pt3d &a_vec1, const Pt3d &a_vec2)
Perform a dot product of Pt3d's.
int gmIntersectTriangleAndLineSegment (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_t0, const Pt3d &a_t1, const Pt3d &a_t2, Pt3d &a_IntersectPt)
Determine if the line (described by a_pt1 and a_pt2) intersects the triangle (a_t0, a_t1, a_t2).
double gm2DDistanceToLineWithTol (const Pt3d *a_pt1, const Pt3d *a_pt2, double a_x, double a_y, double a_tol)
return the xy distance from (a_x,a_y) to line through (a_pt1, a_pt2)
void gmGetConvexHull (const VecPt3d &a_pts, VecPt3d &a_hull, bool a_includeOn)
Calculate convex hull using Monotone chain aka Andrew's algorithm.
static double iDistanceToRing (const GmBstRing3d &a_ring, const Pt3d &a_pt)
Return the minimum distance from the point to a line on the ring.
void iCartToBary (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt3, BarycentricVals &a_b)
Converts from Cartesian coordinates to Barycentric coordinates (local triangle coords).
void iGetBarycentricCoords (const Pt3d &a_p, BarycentricVals &a_b, Pt3d &weights)
Calculates weights at the 3 points of a triangle given the location "a_p" and the Barycentric coords of the triangle.
int mxLUDecomp (double **mat, int n, int *indx, double *d)
Decompose an n x n matrix into Upper & Lower trianglar (in place), from "Numerical Recipes in C" p 43.
int mxLUBcksub (double **mat, int n, const int *indx, double *b)
solve [mat]{x} = {b} by back substitution (mat = LU of mat), from "Numerical Recipes in C" p 44.
bool mxiLudcmp3 (double mat[3][3], int indx[3], double *d)
Decomposes a 3 x 3 matrix into Upper & Lower trianglar(in place)
void mxiLubksb3 (const double mat[3][3], const int indx[3], double b[3])
solve [mat]{x} = {b} by back substitution (mat = LU of mat)
bool mxSolveNxN (double **A, double *x, double *b, int n)
Solves the matrix equation [A]*{x}={b} for {x} where [A] is NxN and {x} and {b} are Nx1 vectors. The matrix A is replaced with the LU decomposition of A.
bool mxSolveBandedEquations (double **a, double *x, double *b, int numeqs, int halfbandwidth)
Solves the matrix equation [a][x]=[b] using gauss elimination.
bool mxSolve3x3 (double A[3][3], double x[3], double b[3])
Solves the matrix equation [A]*{x}={b} for {x} where [A] is 3x3 and {x} and {b} are 3x1 vectors.
int mxInvert4x4 (const double matrix[4][4], double inv[4][4])
Compute the inverse of a transformation matrix. Checks for special case of Orthogonal 4x4 and does easy inverse otherwise uses Gauss-Jordan Elimination with full pivoting and scaling with partial unraveling of loops for speed. See Numerical Recipes in C pages 36-37.
void mxPointMult (Pt3d *pt, const double ctm[4][4])
Multiplies a point by a transformation matrix.
void mxCopy4x4 (double copy[4][4], const double matrix[4][4])
Copy a transformation matrix. Simply uses memcpy.
void mxIdent4x4 (double matrix[4][4])
Sets a transformation matrix to identity.
void mxMult4x4 (double product[4][4], const double matrix1[4][4], const double matrix2[4][4])
Multiplies two transformation matrices.
void mxRotate4x4 (double xrot, double yrot, double zrot, double rMatt[4][4])
return a rotation matrix with specified x, y, z rotations z - y - x order
void mxTranslate4x4 (const Pt3d &a_translation, double a_mx[4][4])
return a translation matrix with specified translation z - y - x order
bool trTriangulateIt (TrTriangulator &a_Client)
Do delaunay divide-and-conquer triangulation.
double trArea (const Pt3d &a_pt1, const Pt3d &a_pt2, const Pt3d &a_pt3)
Return the signed planar area of the triangle (CCW Positive).
void trBuildGridTrianglePolys (int rows, int cols, VecPt3d &a_points, VecInt2d &a_polys)
Create something like this:
void trBuildGridPolys (int rows, int cols, VecPt3d &pts, VecInt2d &polys)
Build something like this:
int trIncrementIndex (int i)
Faster than a % operation and we do this a lot.
int trDecrementIndex (int i)
Faster than a % operation and we do this a lot.
void trRenumberOnDelete (const SetInt &a_deleting, VecInt &a_vec)
Boost serialize function.
VecPt3d ConvexHull (const std::vector< Pt3< double >> &a_points)
Returns the convex hull of a set of points (Deprecated).
VecInt ConvexHullWithIndices (const std::vector< int > &a_points, BSHP< XmUGrid > a_ugrid)
Returns the convex hull of a set of points (Deprecated).
bool DoLineSegmentsCross (const std::pair< Pt3< double >, Pt3< double >> &a_segment1, const std::pair< Pt3< double >, Pt3< double >> &a_segment2)
Determine whether 2 line segments intersect (Deprecated).
bool DoLineSegmentsCross (const Pt3< double > &a_segment1Point1, const Pt3< double > &a_segment1Point2, const Pt3< double > &a_segment2Point1, const Pt3< double > &a_segment2Point2)
Determine whether 2 line segments cross (Deprecated).
bool XmEdgesEquivalent (const XmEdge &a_edge1, const XmEdge &a_edge2)
Test if two edges are the same ignoring direction.
BSHP< XmUGrid > TEST_XmUGrid1Left90Tri ()
Builds a 1 cell (left 90 degree triangle) 2D XmUGrid for testing.
BSHP< XmUGrid > TEST_XmUGridSimpleQuad ()
Builds a 2 cell (Quad) 2D XmUGrid for testing.
BSHP< XmUGrid > TEST_XmUGrid2dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
BSHP< XmUGrid > TEST_XmUGrid3dLinear ()
Builds an XmUGrid with supported 3D linear cells for testing.
BSHP< XmUGrid > TEST_XmUGridHexagonalPolyhedron ()
Builds a 1 cell hexagon with cell type polyhedron.
BSHP< xms::XmUGrid > TEST_XmUBuildQuadUGrid (int a_rows, int a_cols)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildQuadUGrid (int a_rows, int a_cols, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildHexahedronUgrid (int a_rows, int a_cols, int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildHexahedronUgrid (int a_rows, int a_cols, int a_lays, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildPolyhedronUgrid (int a_rows, int a_cols, int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuildPolyhedronUgrid (int a_rows, int a_cols, int a_lays, const xms::Pt3d &a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
BSHP< xms::XmUGrid > TEST_XmUBuild3DChevronUgrid ()
Builds a UGrid with one 3D Chevron polyhedron.
BSHP< XmUGrid > XmReadUGridFromAsciiFile (const std::string &a_filePath)
Read XmUGrid from an ASCII file.
BSHP< XmUGrid > XmReadUGridFromStream (std::istream &a_inStream)
Read an XmUGrid from ASCII text from an input stream.
void XmWriteUGridToAsciiFile (BSHP< XmUGrid > a_ugrid, const std::string &a_filePath)
Write an XmUGrid to an ASCII file.
void XmWriteUGridToStream (BSHP< XmUGrid > a_ugrid, std::ostream &a_outStream)
Save an XmUGrid ASCII text to output stream.
void XmWriteUGridToStream (const XmUGrid &a_ugrid, std::ostream &a_outStream, bool a_binary)
Save an XmUGrid ASCII text to output stream.
Detailed Description
XMS Namespace.
Enumeration Type Documentation
PtInOutOrOn_enum
enum xms::PtInOutOrOn_enum
point in, out, or on
Enumerator
PT_ERROR
error
PT_IN
in
PT_OUT
out
PT_ON
on
Definition at line 36 of file geoms.h.
Turn_enum
enum xms::Turn_enum
direction of turn between 3 points
Enumerator
TURN_LEFT
turn left
TURN_RIGHT
turn right
TURN_COLINEAR_180
continue onward
TURN_COLINEAR_0
turns back on same segment
Definition at line 28 of file geoms.h.
Function Documentation
ConvexHull()
std::vector< Pt3d > xms::ConvexHull (const std::vector< Pt3< double >> & a_points)
Returns the convex hull of a set of points (Deprecated).
Parameters
[in] a_points The list of points
Returns
the list of points in the convex hull
Note
a convex hull is the minimum set of points which contains (not connects) all of the points in a set and is convex.
Definition at line 55 of file XmGeometry.cpp.
References gmGetConvexHull().
Referenced by ConvexHullWithIndices().
ConvexHullWithIndices()
VecInt xms::ConvexHullWithIndices (const std::vector< int > & a_points, BSHP< XmUGrid > a_ugrid)
Returns the convex hull of a set of points (Deprecated).
Parameters
[in] a_points The list of indices to points
[in] a_ugrid The ugrid that contains the points.
Returns
the list of indices to points in the convex hull
Note
a convex hull is the minimum set of points which contains (not connects) all of the points in a set and is convex.
Definition at line 70 of file XmGeometry.cpp.
References ConvexHull().
DoLineSegmentsCross() [1/2]
bool xms::DoLineSegmentsCross (const std::pair< Pt3< double >, Pt3< double >> & a_segment1, const std::pair< Pt3< double >, Pt3< double >> & a_segment2)
Determine whether 2 line segments intersect (Deprecated).
Parameters
[in] a_segment1 The first line segment
[in] a_segment2 The second line segment
Returns
true if the line segments intersect
Definition at line 99 of file XmGeometry.cpp.
References gmLinesCross().
DoLineSegmentsCross() [2/2]
bool xms::DoLineSegmentsCross (const Pt3< double > & a_segment1Point1, const Pt3< double > & a_segment1Point2, const Pt3< double > & a_segment2Point1, const Pt3< double > & a_segment2Point2)
Determine whether 2 line segments cross (Deprecated).
Parameters
[in] a_segment1Point1 First point 3d of line segment 1
[in] a_segment1Point2 Second point 3d of line segment 1
[in] a_segment2Point1 First point 3d of line segment 2
[in] a_segment2Point2 Second point 3d of line segment 2
Returns
true if the line segments cross
Definition at line 115 of file XmGeometry.cpp.
References gmLinesCross().
gm2DDistanceToLineWithTol()
double xms::gm2DDistanceToLineWithTol (const Pt3d * a_pt1, const Pt3d * a_pt2, double a_x, double a_y, double a_tol)
return the xy distance from (a_x,a_y) to line through (a_pt1, a_pt2)
Parameters
[in] a_pt1 first point of line segment
[in] a_pt2 second point of line segment
[in] a_x x location of point used to compute distance to line
[in] a_y y location of point used to compute distance to line
[in] a_tol tolerance used in geometric computations
Returns
distance from a_x,a_y to the line (a_pt1, a_pt2)
Definition at line 2177 of file geoms.cpp.
References sqr().
gmAddToExtents() [1/3]
void xms::gmAddToExtents (const Pt3d & a_pt, Pt3d & a_min, Pt3d & a_max)
Compares a_pt to a_min and a_max. If a_pt is less than a_min or greater than a_max, a_min and a_max are updated.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 787 of file geoms.cpp.
Referenced by xms::GmMultiPolyIntersectorImpl::BuildRTree(), xms::GmMultiPolyIntersectorImpl::CalculateBuffer(), xms::TrTinImpl::GetExtents(), xms::XmUGrid::Impl::GetExtentsFromPoints(), gmExtents2D(), gmExtents3D(), and xms::TrTriangulatorPoints::UpdateAreaTolerance().
gmAddToExtents() [2/3]
void xms::gmAddToExtents (const Pt3d & a_pt, Pt2d & a_min, Pt2d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 802 of file geoms.cpp.
gmAddToExtents() [3/3]
void xms::gmAddToExtents (const Pt2d & a_pt, Pt3d & a_min, Pt3d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_pt A point.
[in,out] a_min Minimum.
[in,out] a_max Maximum.
Definition at line 815 of file geoms.cpp.
gmAngleBetween2DVectors() [1/2]
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
Parameters
[in] dxp x of vector p.
[in] dyp y of vector p.
[in] dxn x of vector n.
[in] dyn y of vector n.
Returns
The angle.
Definition at line 603 of file geoms.cpp.
References sqr().
Referenced by gmAngleBetweenEdges().
gmAngleBetween2DVectors() [2/2]
double xms::gmAngleBetween2DVectors (double dxp, double dyp, double dxn, double dyn, double a_magn, double a_magp)
Returns the angle (0-2PI) in radians between the edges p and n based on a ccw rotation from p to n.
Parameters
[in] dxp x of vector p.
[in] dyp y of vector p.
[in] dxn x of vector n.
[in] dyn y of vector n.
[in] a_magn Magnitude of n.
[in] a_magp Magnitude of p.
Returns
The angle.
Definition at line 622 of file geoms.cpp.
References gmCross2D(), and XM_PI.
gmAngleBetweenEdges() [1/2]
double xms::gmAngleBetweenEdges (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
Returns
The angle.
Definition at line 655 of file geoms.cpp.
References gmAngleBetween2DVectors().
Referenced by xms::TrTinImpl::SwapEdge().
gmAngleBetweenEdges() [2/2]
double xms::gmAngleBetweenEdges (const Pt2d & p1, const Pt2d & p2, const Pt2d & p3)
Returns the ccw angle (0-2pi) between p2-p1 and p2-p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
Returns
The angle.
Definition at line 672 of file geoms.cpp.
References gmAngleBetween2DVectors().
gmArrayToVecPt3d()
VecPt3d xms::gmArrayToVecPt3d (double * a_array, int a_size)
Useful in testing to create a VecPt3d from a C array of xy pairs.
Parameters
[in] a_array Array of xy pairs ([x][y][x][y]...).
[in] a_size Array size.
Returns
Vector of Pt3d.
Definition at line 1590 of file geoms.cpp.
Referenced by GmPolygonUnitTests::SetUpPolyWithHole().
gmBaryPrepare()
int xms::gmBaryPrepare (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, const Pt3d * norm, Pt3d * orig, double coef[6], int * dir, bool flag)
For a tri - compute dir & coefs to compute Barycentric coords.
Parameters
p1 = 1st point of triangle.
p2 = 2nd point of triangle.
p3 = 3rd point of triangle.
norm = triangle normal.
orig = triangle origin (min xyz of p1, p2 and p3).
coef = ?
dir = 0 if norm points to x, 1 if to y, 2 if to z.
flag = if true, origin will be computed from the triangle. If false, just calculate the coefficients and the origin is zero.
Returns
XM_SUCCESS or XM_FAILURE.
Definition at line 315 of file geoms.cpp.
References Mmin(), and XM_SUCCESS.
Referenced by iCartToBary().
gmBisectingAngle()
double xms::gmBisectingAngle (const Pt3d & a_p1, const Pt3d & a_p2, const Pt3d & a_p3)
Returns the angle (0-2pi) which bisects the edges p2-p1 and p2-p3 based on a ccw rotation from edge 1 to edge 2.
Parameters
[in] a_p1 The first point defining the edge (a_p1:a_p2)
[in] a_p2 The second point defining two edges (a_p1:a_p2, a_p2:a_p3)
[in] a_p3 The third point defining the edge (a_p2:a_p3)
Returns
angle that bisects the edges
Definition at line 1901 of file geoms.cpp.
References gmCross2D(), sqr(), and XM_PI.
gmBoxesOverlap2d()
bool xms::gmBoxesOverlap2d (const Pt3d & a_b1Min, const Pt3d & a_b1Max, const Pt3d & a_b2Min, const Pt3d & a_b2Max)
finds if 2 boxes overlap in 2d
Parameters
[in] a_b1Min Min x,y of first box
[in] a_b1Max Max x,y of first box
[in] a_b2Min Min x,y of second box
[in] a_b2Max Max x,y of second box
Returns
true if the boxes overlap
Definition at line 79 of file geoms.cpp.
gmCalculateNormalizedPlaneCoefficients() [1/2]
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3, double * a, double * b, double * c, double * d)
Calculates the plane coefficients for a triangle. Given point references calculate coefficents for plane (ax+by+cz+d=0).
Parameters
[in] p1 First point.
[in] p2 Second point.
[in] p3 Third point.
[out] a Coefficient a.
[out] b Coefficient b.
[out] c Coefficient c.
[out] d Coefficient d.
Definition at line 105 of file geoms.cpp.
gmCalculateNormalizedPlaneCoefficients() [2/2]
void xms::gmCalculateNormalizedPlaneCoefficients (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, double * a, double * b, double * c, double * d)
Calculates the plane coefficients for a triangle. Given point pointers calculate coefficents for plane (ax+by+cz+d=0).
Parameters
[in] p1 First point.
[in] p2 Second point.
[in] p3 Third point.
[out] a Coefficient a.
[out] b Coefficient b.
[out] c Coefficient c.
[out] d Coefficient d.
Definition at line 127 of file geoms.cpp.
gmCartToBary()
int xms::gmCartToBary (const Pt3d * cart, const Pt3d * orig, double coef[6], int dir, Pt3d * bary)
Compute Barycentric coords for point. Use gmBaryPrepare to get the coefficients and direction.
Parameters
[in] cart cart?
[in] orig orig?
[in] coef 6 coefficients.
[in] dir Direction.
[out] bary point?
Returns
XM_SUCCESS (always it seems)
Definition at line 275 of file geoms.cpp.
References XM_SUCCESS.
Referenced by iGetBarycentricCoords().
gmCircumcircleWithTol()
bool xms::gmCircumcircleWithTol (const Pt3d * pt1, const Pt3d * pt2, const Pt3d * pt3, double * xc, double * yc, double * r2, double tol)
Computes center & radius squared for circumcircle of triangle made by the three points.
Parameters
pt1 first of 3 locations defining a triangle
pt2 second of 3 locations defining a triangle
pt3 third of 3 locations defining a triangle
xc circumcenter x coord
yc circumcenter y coord
r2 radius squared of circumcircle
tol tolerance for geometric comparison
Returns
false on error (triangle has zero area), otherwise true
Definition at line 218 of file geoms.cpp.
References sqr().
Referenced by gmPtInCircumcircle().
gmColinearWithTol()
bool xms::gmColinearWithTol (const Pt3d & p1, const Pt3d & p2, const Pt3d & p3, const double tol)
Returns true if (the three vertices are gmColinear. Result should be insensitive to the order of the vertices.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
[in] tol Tolerance
Returns
true if colinear.
Definition at line 393 of file geoms.cpp.
References gmOnLineWithTol().
Referenced by gmIntersectLineSegmentsWithTol().
gmComponentMagnitudes()
void xms::gmComponentMagnitudes (double * a_x, double * a_y, double * a_mag, double * a_dir, bool a_tomagdir)
converts the magnitude and angle to xy components or vice versa
Parameters
[in,out] a_x vector x component either specified or calculated from a_mag, a_dir
[in,out] a_y vector y component either specified or calculated from a_mag, a_dir
[in,out] a_mag vector magnitude either specified or calculated from a_x, a_y
[in,out] a_dir vector direction (degrees) either specified or calculated from a_x, a_y
[in] a_tomagdir flag, when true a_x, a_y are used to calculate a_mag, a_dir; when false a_mag, a_dir are used to calculate a_x, a_y
Definition at line 1941 of file geoms.cpp.
References sqr(), XM_PI, and XM_ZERO_TOL.
gmComputeCentroid()
Pt3d xms::gmComputeCentroid (const VecPt3d & a_points)
Computes the centroid of points (but not of a polygon). Shouldn't pass an empty vector (no checks are performed).
Parameters
[in] a_points Points.
Returns
Centroid.
Definition at line 895 of file geoms.cpp.
Referenced by xms::GmMultiPolyIntersectionSorterTerse::RemoveDuplicateEdges(), GeomsXmsngUnitTests::test_gmComputeCentroid(), and trBuildGridTrianglePolys().
gmComputeDeviationInDirection()
double xms::gmComputeDeviationInDirection (const Pt3d & a_p0, const Pt3d & a_p1, const Pt3d & a_p2)
Computes the deviation in direction from one seg to next seg 1 is from a_p0 to a_p1 seg 2 is from a_p1 to a_p2.
Parameters
[in] a_p0 1st point on 1st segment.
[in] a_p1 2nd point on 1st segment and 1st point on second segment.
[in] a_p2 2nd point on 2nd segment.
Returns
Returns value between 0 and PI. note: magnitude zero would cause problem - return PI in this case returning PI would indicate that there could be discontinuity this is a streamlined version of gmAngleBetweenEdges that function
computes a directed internal difference
requires an extra cross product, several compares & multiplies this function still has the sqrt and acos, so maybe not a big deal
Definition at line 697 of file geoms.cpp.
References Mmax(), Mmin(), and XM_PI.
gmComputePolygonCentroid()
Pt3d xms::gmComputePolygonCentroid (const VecPt3d & pts)
Computes the plan view centroid of a non-self-intersecting polygon.
Parameters
[in] pts Points.
Returns
Centroid.
Definition at line 908 of file geoms.cpp.
Referenced by xms::XmUGrid::Impl::GetCellCentroid(), and GeomsXmsngUnitTests::test_gmComputePolygonCentroid().
gmComputeXyTol()
double xms::gmComputeXyTol (const Pt3d & a_mn, const Pt3d & a_mx)
Given extents (min, max), compute a tolerance for the xy plane to be used with geometric functions.
Parameters
a_mn Minimum.
a_mx Maximum.
Returns
Tolerance.
Definition at line 1262 of file geoms.cpp.
References gmXyDistance().
Referenced by xms::TrBreaklineAdderImpl::ComputeTolerance(), and xms::TrTriangulatorPoints::UpdateAreaTolerance().
gmConvertAngleToBetween0And360()
double xms::gmConvertAngleToBetween0And360 (double a_angle, bool a_InDegrees)
given an angle, this function will return the corresponding angle that matches it in the range of 0 deg to 360 deg
Parameters
[in] a_angle The angle to convert to 0 to 360
[in] a_InDegrees Flag to tell if the angle is in degrees vs radians
Returns
an angle between 0 and 360
Definition at line 1997 of file geoms.cpp.
References GTEQ_TOL(), LT_TOL(), and XM_PI.
gmCounterClockwiseTri()
bool xms::gmCounterClockwiseTri (const Pt3d & vtx0, const Pt3d & vtx1, const Pt3d & vtx2)
Returns true if the triangle is wrapped counter clockwise.
Parameters
[in] vtx0 Vertex 0.
[in] vtx1 Vertex 1.
[in] vtx2 Vertex 2.
Returns
true if vertex order is counter clockwise.
Definition at line 564 of file geoms.cpp.
References trArea().
Referenced by xms::TrTinImpl::SwapEdge().
gmCreateVector()
Pt3d xms::gmCreateVector (const Pt3d & a_p1, const Pt3d & a_p2)
creates a vector from a_p1 to a_p2
Parameters
[in] a_p1 The first point
[in] a_p2 The second point
Returns
a vector with x,y,z components representing the direction from a_p1 to a_p2
Definition at line 1982 of file geoms.cpp.
gmCross2D() [1/2]
double xms::gmCross2D (const double & dx1, const double & dy1, const double & dx2, const double & dy2)
Returns the cross product of two 2-d vectors.
Parameters
dx1 x component of vector 1
dy1 y component of vector 1
dx2 x component of vector 2
dy2 y component of vector 2
Returns
cross product of 2 vectors vector 1 = dx1i + dy1j vector 2 = dx2i + dy2j
Definition at line 579 of file geoms.cpp.
Referenced by gmAngleBetween2DVectors(), gmBisectingAngle(), and gmLinesCross().
gmCross2D() [2/2]
double xms::gmCross2D (const Pt3d & a_origin, const Pt3d & a_A, const Pt3d & a_B)
2D cross product of two points
Parameters
[in] a_origin origin point for the "vectors"
[in] a_A first vector
[in] a_B second vector
Returns
the cross product
Definition at line 590 of file geoms.cpp.
gmCross3D()
void xms::gmCross3D (const Pt3d & a_vec1, const Pt3d & a_vec2, Pt3d * a_vec3)
Perform a cross product of Pt3d's.
Parameters
[in] a_vec1 First vector to cross
[in] a_vec2 Second vector to cross
[out] a_vec3 Resulting cross product
Definition at line 2034 of file geoms.cpp.
Referenced by gmIntersectTriangleAndLineSegment().
gmDot3D()
double xms::gmDot3D (const Pt3d & a_vec1, const Pt3d & a_vec2) inline
Perform a dot product of Pt3d's.
Parameters
[in] a_vec1 First vector to dot
[in] a_vec2 Second vector to dot
Returns
The dot product has the geometric interpretation as the length of the projection of a_vec1 onto the unit vector a_vec2 when the two vectors are placed so that their tails coincide.
Definition at line 2048 of file geoms.cpp.
Referenced by gmIntersectTriangleAndLineSegment().
gmEnvelopeOfPts()
void xms::gmEnvelopeOfPts (const VecPt3d & a_pts, Pt3d & a_min, Pt3d & a_max)
Calculates the envelope of a vector of points.
Parameters
[in] a_pts Array of points
[out] a_min Min x,y,z of the points
[out] a_max Max x,y,z of the points
Definition at line 1606 of file geoms.cpp.
References XM_ENSURE_TRUE.
gmEqualPointsXY() [1/5]
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2, double tolerance)
Returns true if the points are equal to within gmXyTol().
Parameters
x1 x of point 1.
y1 y of point 1.
x2 x of point 2.
y2 y of point 2.
tolerance tolerance.
Returns
true if equal.
Definition at line 1308 of file geoms.cpp.
Referenced by gmEqualPointsXY(), gmInsideOfLineWithTol(), gmInsideOrOnLineWithTol(), gmIntersectLineSegmentsWithTol(), gmOnLineWithTol(), and xms::GmMultiPolyIntersectorImpl::PointsOnSegment().
gmEqualPointsXY() [2/5]
bool xms::gmEqualPointsXY (double x1, double y1, double x2, double y2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
x1 x of point 1.
y1 y of point 1.
x2 x of point 2.
y2 y of point 2.
Returns
true if equal.
Definition at line 1327 of file geoms.cpp.
References gmEqualPointsXY(), and gmXyTol().
gmEqualPointsXY() [3/5]
bool xms::gmEqualPointsXY (const Pt2d & a_pt1, const Pt2d & a_pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1338 of file geoms.cpp.
References gmEqualPointsXY().
gmEqualPointsXY() [4/5]
bool xms::gmEqualPointsXY (const Pt3d & a_pt1, const Pt3d & a_pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1349 of file geoms.cpp.
References gmEqualPointsXY().
gmEqualPointsXY() [5/5]
bool xms::gmEqualPointsXY (const Pt2i & point1, const Pt2i & point2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
point1 Point 1.
point2 Point 2.
Returns
true if equal within tolerance.
Definition at line 1359 of file geoms.cpp.
gmEqualPointsXYZ() [1/3]
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2, double tolerance)
Returns true if the points are equal to within tolerance.
Parameters
x1 x of point 1.
y1 y of point 1.
z1 z of point 1.
x2 x of point 2.
y2 y of point 2.
z2 z of point 2.
tolerance tolerance.
Returns
true if equal.
Definition at line 1376 of file geoms.cpp.
Referenced by gmEqualPointsXYZ().
gmEqualPointsXYZ() [2/3]
bool xms::gmEqualPointsXYZ (double x1, double y1, double z1, double x2, double y2, double z2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
x1 x of point 1.
y1 y of point 1.
z1 z of point 1.
x2 x of point 2.
y2 y of point 2.
z2 z of point 2.
Returns
true if equal within tolerance.
Definition at line 1398 of file geoms.cpp.
References gmEqualPointsXYZ(), and gmXyTol().
gmEqualPointsXYZ() [3/3]
bool xms::gmEqualPointsXYZ (const Pt3d & pt1, const Pt3d & pt2, double tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
pt1 Point 1.
pt2 Point 2.
tol tolerance.
Returns
true if equal within tolerance.
Definition at line 1409 of file geoms.cpp.
References gmEqualPointsXYZ().
gmExtents2D() [1/2]
void xms::gmExtents2D (const VecPt3d & a_points, Pt2d & a_min, Pt2d & a_max)
Get the 2D extents of a vector of points.
Parameters
[in] a_points The points.
[out] a_min Minimum point (xy) of bounding rectangle.
[out] a_max Maximum point (xy) of bounding rectangle.
Definition at line 1821 of file geoms.cpp.
References gmAddToExtents(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
gmExtents2D() [2/2]
void xms::gmExtents2D (const VecPt3d & a_points, Pt3d & a_min, Pt3d & a_max)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_points Vector of points.
[in,out] a_min Minimum value.
[in,out] a_max Maximum value.
Definition at line 1838 of file geoms.cpp.
References gmAddToExtents(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
gmExtents3D()
void xms::gmExtents3D (const VecPt3d & a_points, Pt3d & a_min, Pt3d & a_max)
Get the 3D extents of a vector of points.
Parameters
[in] a_points The points.
[out] a_min Minimum point (xyz) of bounding box.
[out] a_max Maximum point (xyz) of bounding box.
Definition at line 1856 of file geoms.cpp.
References gmAddToExtents(), and XM_ENSURE_TRUE_VOID_NO_ASSERT.
gmFindClosestPtOnSegment()
double xms::gmFindClosestPtOnSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt, Pt3d & a_newpt, const double a_tol)
Finds the closest point to another point on a segment.
Parameters
[in] a_pt1 First point of segment
[in] a_pt2 Second point of segment
[in] a_pt Point used to find closest point on the segment
[out] a_newpt The point on the segment (a_pt1, a_pt2) that is closest to a_pt.
[in] a_tol Tolerance
Returns
parametric value along the line a_pt1, a_pt2 that is the location of a_newpt.
Definition at line 1714 of file geoms.cpp.
References gmPtDistanceAlongSegment().
gmGetConvexHull()
void xms::gmGetConvexHull (const VecPt3d & a_pts, VecPt3d & a_hull, bool a_includeOn)
Calculate convex hull using Monotone chain aka Andrew's algorithm.
Parameters
[in] a_pts The input points.
[out] a_hull The convex hull polygon. First point is NOT repeated.
[in] a_includeOn Should points on the hull's line segments be included?
Definition at line 2211 of file geoms.cpp.
References gmTurn().
Referenced by ConvexHull(), xms::XmUGrid::Impl::GetPlanViewPolygon3d(), and GeomsXmsngUnitTests::testConvexHull().
gmInsideOfLineWithTol()
bool xms::gmInsideOfLineWithTol (const Pt3d & a_vertex1, const Pt3d & a_vertex2, const Pt3d & a_oppositevertex, const double a_x, const double a_y, const double a_tol)
Returns TRUE if the Point on the same side of the line (defined by vertex1 and vertex2) as oppositevertex.
Parameters
[in] a_vertex1 : First point on the line segment
[in] a_vertex2 : Second point on the line segment
[in] a_oppositevertex : Point on one side of the line
[in] a_x : X location of the point being tested
[in] a_y : Y location of the point being tested
[in] a_tol : Tolerance for degenerate cases
Returns
true if the a_x, a_y are inside the line defined by a_vertex1 and a_vertex2. Inside is defined as the opposite side of a_oppositevertex
Definition at line 1782 of file geoms.cpp.
References gmEqualPointsXY(), and sqr().
gmInsideOrOnLineWithTol()
bool xms::gmInsideOrOnLineWithTol (const Pt3d * p1, const Pt3d * p2, const Pt3d * inpoint, const double x, const double y, const double tol, double * dist)
Returns true if the (x,y) is on the line segment (p1,p2) or on the same side of the line as "inpoint". ASSERTs in debug if "inpoint" is on the line (within tol).
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] inpoint Point on same side of line as xy if true is returned.
[in] x x of point.
[in] y y of point.
[in] tol Tolerance.
[out] dist How far "outside" the point is. A negative distance indicates point is in by that distance.
Returns
true if in.
Definition at line 1450 of file geoms.cpp.
References gmEqualPointsXY(), Mfabs(), and sqr().
Referenced by gmPointInTriangleWithTol().
gmIntersectLineSegmentsWithTol()
bool xms::gmIntersectLineSegmentsWithTol (const Pt3d & one1, const Pt3d & one2, const Pt3d & two1, const Pt3d & two2, double * xi, double * yi, double * zi1, double * zi2, double tol)
Intersects the plan projection of two line segments.
Parameters
one1 first point on segment 1
one2 second point on segment 1
two1 first point on segment 2
two2 second point on segment 2
xi x coord of intersection
yi y coord of intersection
zi1 z coord of intersection on segment 1
zi2 z coord of intersection on segemnt 2
tol tolerance for geometric comparison
segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
Returns
true if lines intersect, else false
Definition at line 420 of file geoms.cpp.
References EQ_TOL(), gmColinearWithTol(), gmEqualPointsXY(), GT_TOL(), and LT_TOL().
Referenced by xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromEdge(), xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromPoint(), and xms::TrBreaklineAdderImpl::ProcessSegmentBySwapping().
gmIntersectTriangleAndLineSegment()
int xms::gmIntersectTriangleAndLineSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_t0, const Pt3d & a_t1, const Pt3d & a_t2, Pt3d & a_IntersectPt)
Determine if the line (described by a_pt1 and a_pt2) intersects the triangle (a_t0, a_t1, a_t2).
Parameters
[in] a_pt1 First point defining a segment
[in] a_pt2 Second point defining a segment
[in] a_t0 First point defining a triangle
[in] a_t1 Second point defining a triangle
[in] a_t2 Third point defining a triangle
[out] a_IntersectPt The point of intersection if the segment and triangle intersect
Returns
-1 if triangle is degenerate (a point or a line) 0 if line does not intersect triangle 1 if line does intersect triangle 2 if line and triangle are in the same plane
Definition at line 2075 of file geoms.cpp.
References gmCross3D(), gmDot3D(), and XM_ZERO_TOL.
gmLinesCross()
bool xms::gmLinesCross (const Pt3d & a_segment1Point1, const Pt3d & a_segment1Point2, const Pt3d & a_segment2Point1, const Pt3d & a_segment2Point2)
Determine whether 2 line segments cross. The segments may touch at the end points.
Parameters
[in] a_segment1Point1 First point 3d of line segment 1
[in] a_segment1Point2 Second point 3d of line segment 1
[in] a_segment2Point1 First point 3d of line segment 2
[in] a_segment2Point2 Second point 3d of line segment 2
Returns
true if the line segments cross
Definition at line 1013 of file geoms.cpp.
References gmCross2D().
Referenced by xms::XmUGrid::Impl::DoEdgesCrossWithPointChange(), DoLineSegmentsCross(), and GeomsXmsngUnitTests::testDoLineSegmentsCross().
gmLinesIntersect()
bool xms::gmLinesIntersect (const Pt3d & one1, const Pt3d & one2, const Pt3d & two1, const Pt3d & two2)
intersects the plan projection of two line segments (bad func name) segment 1 = one1,one2 = one1 + lambda(one2 - one1) segment 2 = two1,two2 = two1 + mu (two2 - two1)
Parameters
one1 first point on first segment
one2 second point on first segment
two1 first point on second segment
two2 second point on second segment
Returns
true if segments intersect, else false
Definition at line 966 of file geoms.cpp.
References GT_TOL(), LT_TOL(), and XM_ZERO_TOL.
gmMiddleZ()
double xms::gmMiddleZ (const VecPt3d & a_points)
Returns the z value halfway between the max and min z. Different from the average z (where many points can skew the average).
Parameters
a_points vector of locations
Returns
Middle z value.
Definition at line 153 of file geoms.cpp.
gmOnLineAndBetweenEndpointsWithTol()
bool xms::gmOnLineAndBetweenEndpointsWithTol (const Pt3d & a_pt1, const Pt3d & a_pt2, const double a_x, const double a_y, double a_tol)
determines if (x,y) is on the line passing through p1 & p2 and between p1 & p2.
Parameters
a_pt1 first location defining segment
a_pt2 second location defining segment
a_x x coord
a_y y coord
a_tol tolerance for comparison
Returns
true if on line segment
Note
For simple test of colinearity, call gmOnLineWithTol or gmColinear
Definition at line 767 of file geoms.cpp.
References gmOnLineWithTol(), Mmax(), and Mmin().
Referenced by xms::GmMultiPolyIntersectorImpl::PointsOnSegment().
gmOnLineWithTol()
bool xms::gmOnLineWithTol (const Pt3d & p1, const Pt3d & p2, const double x, const double y, const double tol)
Determines if a point (x,y) is on the line defined by p1 and p2. Assumes p1 and p2 aren't the same.
Parameters
p1 first location defining a line
p2 second location defining a line
x x coord of point to test
y y coord of point to test
tol tolerance for geometric comparison
Returns
Returns true if the Point is on the line passing through p1 and p2 within the tolerance passed. note: you should always be careful to consider the case when p1 and p2 are very close to each other but not to x,y. in that case this test will almost always fail because it will be more susceptible to roundoff error. if you need to know if three points are colinear you should use the gmColinear function.
Definition at line 732 of file geoms.cpp.
References gmEqualPointsXY(), and sqr().
Referenced by gmColinearWithTol(), and gmOnLineAndBetweenEndpointsWithTol().
gmOrderPointsCounterclockwise() [1/2]
void xms::gmOrderPointsCounterclockwise (const VecPt3d & a_pts, VecInt & a_ccwOrder, int a_startindex)
Orders array of points counter clockwise. Given non-empty array of points. array of point indices ordered counter clockwise based on the angle from the centroid where angle starts at point at startindex.
Parameters
[in] a_pts Array of points
[out] a_ccwOrder Array of indices to points
[in] a_startindex Starting position in arrays
Definition at line 1635 of file geoms.cpp.
Referenced by gmOrderPointsCounterclockwise().
gmOrderPointsCounterclockwise() [2/2]
void xms::gmOrderPointsCounterclockwise (VecPt3d & a_pts)
Overload to gmOrderPointsCounterclockwise.
Parameters
[out] a_pts Array of points
Definition at line 1690 of file geoms.cpp.
References gmOrderPointsCounterclockwise().
gmPerpendicularAngle()
double xms::gmPerpendicularAngle (const Pt3d & a_pt1, const Pt3d & a_pt2)
Returns the angle in radians perpendicular to the two points.
Parameters
[in] a_pt1 The first point defining an edge
[in] a_pt2 The second point defining an edge
Returns
angle perpendicular to the edge
Definition at line 1874 of file geoms.cpp.
References sqr(), and XM_PI.
gmPointInOrOnBox2d()
bool xms::gmPointInOrOnBox2d (const Pt3d & a_bMin, const Pt3d & a_bMax, const Pt3d & a_pt)
finds if a point is in or on a box in 2d
Parameters
[in] a_bMin Min x,y of first box
[in] a_bMax Max x,y of first box
[in] a_pt point being tested
Returns
true if the point is in or on a box
Definition at line 65 of file geoms.cpp.
gmPointInPolygon2D() [1/7]
template<typename T > int xms::gmPointInPolygon2D (const T * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
Determines whether (a_x, a_y) is inside=1, on=0, or outside=-1 the polygon defined by the given vertices.
DON'T repeat the first point at the end of the polygon array
See also
EFastPointInPoly
GmPolygon
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1057 of file geoms.cpp.
Referenced by GmPointInPolyTester_gmPointInPolygon2D::CheckPoint(), gmPointInPolygon2D(), and GeomsXmsngIntermediateTests::test_gmPointInPolygon2D().
gmPointInPolygon2D() [2/7]
int xms::gmPointInPolygon2D (const Pt3d * a_verts, size_t a_num, double a_x, double a_y)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1155 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
gmPointInPolygon2D() [3/7]
int xms::gmPointInPolygon2D (const Pt3d * a_verts, size_t a_num, Pt3d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1166 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
gmPointInPolygon2D() [4/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt2d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1177 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
gmPointInPolygon2D() [5/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt3d a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1188 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
gmPointInPolygon2D() [6/7]
int xms::gmPointInPolygon2D (const Pt2i * a_verts, size_t a_num, Pt2i a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1199 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
gmPointInPolygon2D() [7/7]
int xms::gmPointInPolygon2D (const VecPt3d & a_verts, const Pt3d & a_pt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_pt Point to test.
Returns
1 (inside), 0 (on), or -1 (outside)
Definition at line 1209 of file geoms.cpp.
References gmPointInPolygon2D(), and gmXyTol().
Referenced by GeomsXmsngIntermediateTests::test_gmPointInPolygon2D().
gmPointInPolygon2D< Pt2d >()
template int xms::gmPointInPolygon2D< Pt2d > (const Pt2d * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInPolygon2D< Pt2i >()
template int xms::gmPointInPolygon2D< Pt2i > (const Pt2i * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInPolygon2D< Pt3d >()
template int xms::gmPointInPolygon2D< Pt3d > (const Pt3d * a_verts, const size_t a_num, const double a_x, const double a_y, const double a_tol)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] a_verts The polygon in CW or CCW order (doesn't matter which).
[in] a_num Number of verts in a_verts.
[in] a_x X coordinate of point to test.
[in] a_y Y coordinate of point to test.
[in] a_tol Tolerance.
Returns
1 (inside), 0 (on), or -1 (outside)
gmPointInTriangleWithTol()
bool xms::gmPointInTriangleWithTol (const Pt3d * p1, const Pt3d * p2, const Pt3d * p3, double x, double y, double tol)
Returns true if (x,y) is in the tri formed by p1, p2, p3.
Parameters
[in] p1 Point 1.
[in] p2 Point 2.
[in] p3 Point 3.
[in] x x of point.
[in] y y of point.
[in] tol Tolerance.
Returns
true if in.
Definition at line 1423 of file geoms.cpp.
References gmInsideOrOnLineWithTol().
gmPolygonArea()
double xms::gmPolygonArea (const Pt3d * pts, size_t npoints)
Compute 2d planview projection of area of polygon.
Parameters
pts locations defining the polygon
npoints number of pts
Returns
Area of the polygon.
CCW = positive area, CW = negative. Don't repeat the last point.
Definition at line 1537 of file geoms.cpp.
Referenced by xms::XmUGrid::Impl::GetOrientationFromArea().
gmPtDistanceAlongSegment()
double xms::gmPtDistanceAlongSegment (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt, const double a_tol)
Finds the distance along a segment for the location closest to a_pt.
Parameters
[in] a_pt1 First point of segment
[in] a_pt2 Second point of segment
[in] a_pt Point used to find closest point on the segment
[in] a_tol Tolerance
Returns
parametric value along the line a_pt1, a_pt2 that is the closest location to a_pt.
Definition at line 1749 of file geoms.cpp.
Referenced by xms::GmMultiPolyIntersectorImpl::ComputeTValues(), and gmFindClosestPtOnSegment().
gmPtInCircumcircle()
PtInOutOrOn_enum xms::gmPtInCircumcircle (const Pt3d & pt, Pt3d circumcirclePts[3])
Is a given point inside a circumcircle defined by three points?
Parameters
pt The point.
circumcirclePts 3 points on the circumcircle.
Returns
PtInOutOrOn_enum
Definition at line 172 of file geoms.cpp.
References gmCircumcircleWithTol(), gmXyTol(), PT_ERROR, PT_IN, PT_ON, PT_OUT, and sqr().
Referenced by xms::TrTinImpl::PointIsInCircumcircle().
gmTurn()
Turn_enum xms::gmTurn (const Pt3d & a_v1, const Pt3d & a_v2, const Pt3d & a_v3, double a_angtol)
Determine if angle a_v1, a_v2, a_v3 is a left turn, a right turn, colinear 180 degrees, or colinear 0 degrees.
Parameters
a_v1 first of 3 locations defining an angle
a_v2 second of 3 locations defining an angle
a_v3 third of 3 locations defining an angle
a_angtol tolerance for comparing angle see notes
Returns
the type of turn defined by the angle
Note
a_angtol was added in August 2014 by AKZ (with consultation by APC). This is the sine of the angle that is considered a turn at all. The default is 0.0017453 (sine 0.1 and sine 179.9). Therefore, this function will only classify two segments as colinear if the angle between edges is less than this tol of the angle between edges is greater than 180-tol. In that case it will determine if the angle is considered to be 180 TURN_COLINEAR_180 or 0 TURN_COLINEAR_0 based on the cosine.
Definition at line 863 of file geoms.cpp.
References TURN_COLINEAR_0, TURN_COLINEAR_180, TURN_LEFT, and TURN_RIGHT.
Referenced by gmGetConvexHull(), and xms::GmMultiPolyIntersectionSorterTerse::RemoveDuplicateEdges().
gmXyDistance() [1/2]
double xms::gmXyDistance (double x1, double y1, double x2, double y2)
Compute the 2d distance between 2 points.
Parameters
x1 x coord of location 1
y1 y coord of location 1
x2 x coord of location 2
y2 y coord of location 2
Returns
Distance between location 1 and 2
Note
See gmActualDistance if you don't want the distance in model units.
Definition at line 832 of file geoms.cpp.
References sqr().
Referenced by xms::GmMultiPolyIntersectorImpl::CalculateBuffer(), xms::TrTinImpl::CheckTriangle(), and gmComputeXyTol().
gmXyDistance() [2/2]
double xms::gmXyDistance (const Pt3d & pt1, const Pt3d & pt2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
[in] pt1 Point 1.
[in] pt2 Point 2.
Returns
Distance.
Definition at line 842 of file geoms.cpp.
References sqr().
gmXyDistanceSquared()
double xms::gmXyDistanceSquared (const Pt3d & pt1, const Pt3d & pt2)
Calculate XY distance between two 3D points.
Parameters
[in] pt1 First point.
[in] pt2 Second point.
Returns
distance squared.
Definition at line 202 of file geoms.cpp.
References sqr().
gmXyTol()
double xms::gmXyTol (bool a_set, double a_value)
Get or set (set first time) global xy tolerance for float operations.
Parameters
a_set True if setting.
a_value The value if setting.
Returns
XY tolerance.
Definition at line 1279 of file geoms.cpp.
Referenced by xms::GmMultiPolyIntersectorImpl::ComputeTValues(), gmEqualPointsXY(), gmEqualPointsXYZ(), gmPointInPolygon2D(), and gmPtInCircumcircle().
gmZTol()
double xms::gmZTol (bool a_set, double a_value)
Get or set (set first time) global z tolerance for float operations.
Parameters
a_set True if setting.
a_value The value if setting.
Returns
Z tolerance.
Definition at line 1292 of file geoms.cpp.
iCartToBary()
void xms::iCartToBary (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt3, BarycentricVals & a_b)
Converts from Cartesian coordinates to Barycentric coordinates (local triangle coords).
Parameters
a_pt1 Point 1.
a_pt2 Point 2.
a_pt3 Point 3.
a_b Barycentric values.
Definition at line 188 of file GmTriSearch.cpp.
References xms::BarycentricVals::coef, xms::BarycentricVals::dir, gmBaryPrepare(), xms::BarycentricVals::orig, xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::GmTriSearchImpl::GetTriBarycentricVals().
iDistanceToRing()
static double xms::iDistanceToRing (const GmBstRing3d & a_ring, const Pt3d & a_pt) static
Return the minimum distance from the point to a line on the ring.
Parameters
[in] a_ring The ring.
[in] a_pt A point.
Returns
The distance.
Definition at line 75 of file GmPolygon.cpp.
Referenced by xms::GmPolygonImpl::MinDistanceToBoundary().
iGetBarycentricCoords()
void xms::iGetBarycentricCoords (const Pt3d & a_p, BarycentricVals & a_b, Pt3d & weights)
Calculates weights at the 3 points of a triangle given the location "a_p" and the Barycentric coords of the triangle.
Parameters
a_p A point
a_b Barycentric values.
weights Weights.
Definition at line 203 of file GmTriSearch.cpp.
References xms::BarycentricVals::coef, xms::BarycentricVals::dir, gmCartToBary(), xms::BarycentricVals::orig, xms::Pt3< T >::x, and xms::Pt3< T >::y.
Referenced by xms::GmTriSearchImpl::FindTriangle().
mxCopy4x4()
void xms::mxCopy4x4 (double copy[4][4], const double matrix[4][4])
Copy a transformation matrix. Simply uses memcpy.
Parameters
copy matrix that will have result of copy
matrix 4x4 matrix to copy
Definition at line 563 of file matrix.cpp.
Referenced by mxInvert4x4(), and mxMult4x4().
mxIdent4x4()
void xms::mxIdent4x4 (double matrix[4][4])
Sets a transformation matrix to identity.
Parameters
matrix matrix to change
Definition at line 571 of file matrix.cpp.
Referenced by mxRotate4x4(), and mxTranslate4x4().
mxiLubksb3()
void xms::mxiLubksb3 (const double mat[3][3], const int indx[3], double b[3])
solve [mat]{x} = {b} by back substitution (mat = LU of mat)
Parameters
mat matrix[3][3]
indx
b vector of solution [mat]{x} = {b}
Definition at line 231 of file matrix.cpp.
Referenced by mxSolve3x3().
mxiLudcmp3()
bool xms::mxiLudcmp3 (double mat[3][3], int indx[3], double * d)
Decomposes a 3 x 3 matrix into Upper & Lower trianglar(in place)
Parameters
mat matrix[3][3]
indx
d determinant of matrix
Returns
false if errors are encountered else true
Definition at line 157 of file matrix.cpp.
References xmlog::debug, and XM_LOG.
Referenced by mxSolve3x3().
mxInvert4x4()
int xms::mxInvert4x4 (const double matrix[4][4], double inv[4][4])
Compute the inverse of a transformation matrix. Checks for special case of Orthogonal 4x4 and does easy inverse otherwise uses Gauss-Jordan Elimination with full pivoting and scaling with partial unraveling of loops for speed. See Numerical Recipes in C pages 36-37.
Parameters
matrix matrix[4][4] to invert
inv inverse of matrix
Returns
XM_FAILURE if errors are encountered else XM_SUCCESS
Definition at line 422 of file matrix.cpp.
References xmlog::error, mxCopy4x4(), XM_FAILURE, XM_LOG, and XM_SUCCESS.
mxLUBcksub()
int xms::mxLUBcksub (double ** mat, int n, const int * indx, double * b)
solve [mat]{x} = {b} by back substitution (mat = LU of mat), from "Numerical Recipes in C" p 44.
Parameters
mat matrix[n][n]
n dimension of matrix mat
indx
b vector of solution [mat]{x} = {b}
Returns
XM_SUCCESS
Definition at line 122 of file matrix.cpp.
References XM_SUCCESS.
Referenced by mxSolveNxN().
mxLUDecomp()
int xms::mxLUDecomp (double ** mat, int n, int * indx, double * d)
Decompose an n x n matrix into Upper & Lower trianglar (in place), from "Numerical Recipes in C" p 43.
Parameters
mat matrix[n][n]
n dimension of matrix mat
indx
d matrix determinant
Returns
XM_FAILURE if errors encountered else XM_SUCCESS
Definition at line 47 of file matrix.cpp.
References XM_FAILURE, and XM_SUCCESS.
Referenced by mxSolveNxN().
mxMult4x4()
void xms::mxMult4x4 (double product[4][4], const double matrix1[4][4], const double matrix2[4][4])
Multiplies two transformation matrices.
Parameters
product result of matrix1*matrix2
matrix1 [4][4] matrix multiplied by matrix2
matrix2 [4][4] matrix multiplied by matrix1
Definition at line 585 of file matrix.cpp.
References mxCopy4x4().
mxPointMult()
void xms::mxPointMult (Pt3d * pt, const double ctm[4][4])
Multiplies a point by a transformation matrix.
Parameters
pt point to multiply
ctm transform matrix[4][4].
Definition at line 549 of file matrix.cpp.
mxRotate4x4()
void xms::mxRotate4x4 (double xrot, double yrot, double zrot, double rMatt[4][4])
return a rotation matrix with specified x, y, z rotations z - y - x order
Parameters
xrot x rotation amount
yrot y rotation amount
zrot z rotation amount
rMatt matrix to be built
Definition at line 611 of file matrix.cpp.
References mxIdent4x4(), and XM_PI.
mxSolve3x3()
bool xms::mxSolve3x3 (double A[3][3], double x[3], double b[3])
Solves the matrix equation [A]*{x}={b} for {x} where [A] is 3x3 and {x} and {b} are 3x1 vectors.
Parameters
A matrix[3][3]
x vector[3]
b vector[3] of solution [A]{x} = {b}
Returns
XM_FAILURE if errors are encountered else XM_SUCCESS
Definition at line 399 of file matrix.cpp.
References mxiLubksb3(), and mxiLudcmp3().
mxSolveBandedEquations()
bool xms::mxSolveBandedEquations (double ** a, double * x, double * b, int numeqs, int halfbandwidth)
Solves the matrix equation [a][x]=[b] using gauss elimination.
Parameters
a matrix[n][n]
x vector nx1
b vector of solution [A]{x} = {b}
numeqs number of equations
halfbandwidth
Note
Assumes that [a] is a banded symmetric matrix with only the upper half stored. If a matrix is banded and symmetric, only values at or above the main diagonal need to be stored. When setting up the matrix, the indices in the equivalent full matrix are mapped to the indices in the banded matrix with the following formula (i,j)=(i,j-i+1) where j is the row number and i is the column number.
Returns
false if errors encountered else true
Definition at line 325 of file matrix.cpp.
mxSolveNxN()
bool xms::mxSolveNxN (double ** A, double * x, double * b, int n)
Solves the matrix equation [A]*{x}={b} for {x} where [A] is NxN and {x} and {b} are Nx1 vectors. The matrix A is replaced with the LU decomposition of A.
Parameters
A matrix[n][n]
x vector nx1
b vector of solution [A]{x} = {b}
n size of matrix A
Returns
false if errors encountered else true
Definition at line 268 of file matrix.cpp.
References mxLUBcksub(), mxLUDecomp(), and XM_FAILURE.
mxTranslate4x4()
void xms::mxTranslate4x4 (const Pt3d & a_translation, double a_mx[4][4])
return a translation matrix with specified translation z - y - x order
Parameters
a_translation translation distances in x, y, and z.
a_mx matrix to be built
Definition at line 638 of file matrix.cpp.
References mxIdent4x4().
TEST_XmUBuild3DChevronUgrid()
BSHP< xms::XmUGrid > xms::TEST_XmUBuild3DChevronUgrid ()
Builds a UGrid with one 3D Chevron polyhedron.
Returns
Returns the UGrid.
Definition at line 3972 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testGetCellPlanViewPolygon().
TEST_XmUBuildHexahedronUgrid() [1/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildHexahedronUgrid (int a_rows, int a_cols, int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
Returns
Returns the UGrid.
Definition at line 3809 of file XmUGrid.cpp.
Referenced by XmUGridUnitTests::testCell3dFunctionCaching(), XmUGridUnitTests::testGetCell3dFaceAdjacentCell(), XmUGridUnitTests::testGetCell3dFaceOrientationHexahedrons(), XmUGridUnitTests::testGetCellEdgeAdjacentCells(), XmUGridUnitTests::testGetExtents(), and XmUGridUnitTests::testIsCellValidWithPointChange().
TEST_XmUBuildHexahedronUgrid() [2/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildHexahedronUgrid (int a_rows, int a_cols, int a_lays, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
[in] a_origin locatGetPointLocation UGrid begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 3822 of file XmUGrid.cpp.
References xms::XmUGrid::New().
TEST_XmUBuildPolyhedronUgrid() [1/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildPolyhedronUgrid (int a_rows, int a_cols, int a_lays)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
Returns
Returns the UGrid.
Definition at line 3875 of file XmUGrid.cpp.
Referenced by XmUGridUnitTests::testGetCell3dFaceOrientationHexahedrons(), XmUGridUtilsTests::testLargeUGridBinarySpeed(), and XmUGridUnitTests::testLargeUGridLinkSpeed().
TEST_XmUBuildPolyhedronUgrid() [2/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildPolyhedronUgrid (int a_rows, int a_cols, int a_lays, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_lays number of layers in UGrid
[in] a_origin location wGetPointLocationd begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 3888 of file XmUGrid.cpp.
References xms::XmUGrid::New().
TEST_XmUBuildQuadUGrid() [1/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildQuadUGrid (int a_rows, int a_cols)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
Returns
Returns the UGrid.
Definition at line 3761 of file XmUGrid.cpp.
TEST_XmUBuildQuadUGrid() [2/2]
BSHP< xms::XmUGrid > xms::TEST_XmUBuildQuadUGrid (int a_rows, int a_cols, const xms::Pt3d & a_origin)
Builds a UGrid of Quads at 1 spacing for rows & cols specified.
Parameters
[in] a_rows number of rows in UGrid
[in] a_cols number of columns in UGrid
[in] a_origin location where the UGrid begins (min x, min y, min z)
Returns
Returns the UGrid.
Definition at line 3773 of file XmUGrid.cpp.
References xms::XmUGrid::New().
TEST_XmUGrid1Left90Tri()
BSHP< xms::XmUGrid > xms::TEST_XmUGrid1Left90Tri ()
Builds a 1 cell (left 90 degree triangle) 2D XmUGrid for testing.
2
| \
|  \
|   \
0----1
Returns
Returns a builder for the UGrid.
Definition at line 3631 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testOperators(), XmUGridUtilsTests::testReadBasicUGrid(), XmUGridUtilsTests::testReadReadyAtNextLine(), and XmUGridUtilsTests::testWriteBasicUGrid().
TEST_XmUGrid2dLinear()
BSHP< xms::XmUGrid > xms::TEST_XmUGrid2dLinear ()
Builds an XmUGrid with supported 1D and 2D linear cells for testing.
Returns
Returns the XmUGrid.
[snip_test_2DShapes]
[snip_test_2DShapes]
Definition at line 3671 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testGetCell3dFaceCount(), XmUGridUnitTests::testGetCell3dFacePointCount(), XmUGridUnitTests::testGetCell3dFacePoints(), XmUGridUnitTests::testGetCellAdjacentCells(), XmUGridUnitTests::testGetCellDimension(), XmUGridUnitTests::testGetCellEdge(), XmUGridUnitTests::testGetCellEdgeCount(), XmUGridUnitTests::testGetCellPlanViewPolygon(), XmUGridUnitTests::testGetCellPoints(), XmUGridUnitTests::testGetCellType(), XmUGridUnitTests::testGetExtents(), XmUGridUnitTests::testGetPointAdjacentCells(), XmUGridUtilsTests::testLinear2dWriteThenRead(), and XmUGridUtilsTests::testWriteLinear2dCells().
TEST_XmUGrid3dLinear()
BSHP< xms::XmUGrid > xms::TEST_XmUGrid3dLinear ()
Builds an XmUGrid with supported 3D linear cells for testing.
Returns
Returns the XmUGrid.
[snip_test_3DShapes]
[snip_test_3DShapes]
Definition at line 3697 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testCell3dFaceFunctions(), XmUGridUnitTests::testGetCell3dFaceCount(), XmUGridUnitTests::testGetCell3dFacePointCount(), XmUGridUnitTests::testGetCell3dFacePoints(), XmUGridUnitTests::testGetCellAdjacentCells(), XmUGridUnitTests::testGetCellDimension(), XmUGridUnitTests::testGetCellEdge(), XmUGridUnitTests::testGetCellEdgeCount(), XmUGridUnitTests::testGetCellPlanViewPolygon(), XmUGridUnitTests::testGetCellPoints(), XmUGridUnitTests::testGetCellType(), XmUGridUnitTests::testGetExtents(), XmUGridUnitTests::testGetPointAdjacentCells(), XmUGridUtilsTests::testLinear3dWriteThenRead(), XmUGridUtilsTests::testReadVersion1Dot0File(), XmUGridUtilsTests::testWriteLinear3dCells(), XmUGridUtilsTests::testWriteThenReadUGridBinary(), XmUGridUtilsTests::testWriteThenReadUGridFile(), and XmUGridUtilsTests::testWriteThenReadUGridFileToAscii().
TEST_XmUGridHexagonalPolyhedron()
BSHP< xms::XmUGrid > xms::TEST_XmUGridHexagonalPolyhedron ()
Builds a 1 cell hexagon with cell type polyhedron.
Returns
Returns the UGrid.
Definition at line 3732 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUtilsTests::testReadPolyhedronUGrid(), and XmUGridUtilsTests::testWritePolyhedronUGrid().
TEST_XmUGridSimpleQuad()
BSHP< xms::XmUGrid > xms::TEST_XmUGridSimpleQuad ()
Builds a 2 cell (Quad) 2D XmUGrid for testing.
0-----1-----2
|  0  |  1  |
3-----4-----5
|  2  |  3  |
6-----7-----8
Returns
Returns a builder for the UGrid.
Definition at line 3654 of file XmUGrid.cpp.
References xms::XmUGrid::New().
Referenced by XmUGridUnitTests::testCellEdgeAdjacentCellFunctions(), XmUGridUnitTests::testCellEdges(), XmUGridUnitTests::testCellFunctions(), XmUGridUnitTests::testCellstreamFunctions(), XmUGridUnitTests::testEdgeAdjacentCells(), XmUGridUnitTests::testGetCellAdjacentCells(), XmUGridUnitTests::testGetCellEdge(), XmUGridUnitTests::testGetCellEdgeAdjacentCells(), XmUGridUnitTests::testGetCellPoints(), XmUGridUnitTests::testGetPointAdjacentPoints(), XmUGridUnitTests::testGetPointsAdjacentCells(), XmUGridUnitTests::testIsCellValidWithPointChange(), and XmUGridUnitTests::testPointFunctions().
trArea()
double xms::trArea (const Pt3d & a_pt1, const Pt3d & a_pt2, const Pt3d & a_pt3)
Return the signed planar area of the triangle (CCW Positive).
This uses the formula: (-x2*y1 + x3*y1 + x1*y2 - x3*y2 - x1*y3 + x2*y3) / 2 reworked to ensure precision is not lost with large numbers by moving the triangle to the origin by subtracting the first vertex's location from all vertices.
Parameters
[in] a_pt1 First point on triangle.
[in] a_pt2 Second point on triangle.
[in] a_pt3 Third point on triangle.
Returns
The area.
Definition at line 46 of file triangles.cpp.
Referenced by gmCounterClockwiseTri(), xms::TrTriangulatorPoints::ReceiveTriangle(), xms::TrTinImpl::SwapEdge(), and xms::TrTinImpl::TriangleArea().
trBuildGridPolys()
void xms::trBuildGridPolys (int rows, int cols, VecPt3d & pts, VecInt2d & polys)
Build something like this:
///  (0, 0)
///    0-------------1-------------2
///    |             |             |
///    |             |             |
///    |      1      |      2      |
///    |             |             |
///    |             |             |
///    3-------------4-------------5
///                             (20,-10)
///
Parameters
[in] rows Number of rows
[in] cols Number of columns
[out] pts The points.
[out] polys The polygons.
Definition at line 132 of file triangles.cpp.
Referenced by trBuildGridTrianglePolys().
trBuildGridTrianglePolys()
void xms::trBuildGridTrianglePolys (int rows, int cols, VecPt3d & a_points, VecInt2d & a_polys)
Create something like this:
/// (0, 0)
///    0-------------1-------------2
///    |\     4     /|\     8     /|
///    |  \       /  |  \       /  |
///    |    \   /    |    \   /    |
///    |  1   3    3 |  5   4    7 |
///    |    /   \    |    /   \    |
///    |  /       \  |  /       \  |
///    |/     2     \|/     6     \|
///    5-------------6-------------7 2
///                            (20, -10)
///
Parameters
[in] rows Number of rows
[in] cols Number of columns
[out] a_points The points.
[out] a_polys The polygons.
Definition at line 72 of file triangles.cpp.
References gmComputeCentroid(), and trBuildGridPolys().
Referenced by GmMultiPolyIntersectorUnitTests::testAlongEdgesInsideToInside(), GmMultiPolyIntersectorUnitTests::testAlongEdgesOutsideToOutside(), GmMultiPolyIntersectorUnitTests::testEdgeThroughOppositeVertexAtAngle(), GmMultiPolyIntersectorUnitTests::testEndAtEdgeFromAdjacent(), GmMultiPolyIntersectorUnitTests::testInsideToEdgeThenThroughAdjacent(), GmMultiPolyIntersectorUnitTests::testInsideToInside(), GmMultiPolyIntersector2IntermediateTests::testLargeNumPolys(), GmMultiPolyIntersector2IntermediateTests::testLargeNumPolysAndSegments(), GmMultiPolyIntersectorUnitTests::testOutsideToOutside(), GmMultiPolyIntersectorUnitTests::testStartAtEdgeThroughAdjacent(), GmMultiPolyIntersectorUnitTests::testTouchesEdge(), and GmMultiPolyIntersectorUnitTests::testTouchesVertex().
trDecrementIndex()
int xms::trDecrementIndex (int i) inline
Faster than a % operation and we do this a lot.
Parameters
i The index.
Returns
The decremented index.
Definition at line 54 of file triangles.h.
Referenced by xms::TrTinImpl::CheckAndSwap(), xms::TrTinImpl::NextBoundaryPoint(), xms::TrTinImpl::SwapEdge(), and xms::TrTinImpl::TriangleAdjacentToEdge().
trIncrementIndex()
int xms::trIncrementIndex (int i) inline
Faster than a % operation and we do this a lot.
Parameters
i The index.
Returns
The incremented index.
Definition at line 44 of file triangles.h.
Referenced by xms::TrTinImpl::AdjacentTriangle(), xms::TrTinImpl::CheckAndSwap(), xms::TrTinImpl::CheckTriangle(), xms::TrTinImpl::CommonEdgeIndex(), xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromEdge(), xms::TrBreaklineAdderImpl::FindIntersectingEdgeFromPoint(), xms::TrTinImpl::GetBoundaryPoints(), xms::TrOuterTriangleDeleterImpl::MarkNeighbors(), xms::TrTinImpl::OptimizeTriangulation(), xms::TrTinImpl::PreviousBoundaryPoint(), xms::TrBreaklineAdderImpl::ProcessSegmentBySwapping(), xms::TrTinImpl::SwapEdge(), and xms::TrTinImpl::TriangleFromEdge().
trRenumberOnDelete()
void xms::trRenumberOnDelete (const SetInt & a_deleting, VecInt & a_vec)
Boost serialize function.
Renumbers items in a_vec as if deleting items in a_deleting.
Used to renumber m_tris when deleting points. Subtracts 1 from each point index that is greater than or equal to the point index that was deleted. Goes from greatest number being deleted to least so greater numbers get reduced more with each pass.
Parameters
[in] a_deleting Set of numbered things in a_vec being deleted.
[in,out] a_vec Vector of numbered things that gets renumbered.
Definition at line 1376 of file TrTin.cpp.
Referenced by xms::TrTinImpl::DeletePoints().
trTriangulateIt()
bool xms::trTriangulateIt (TrTriangulator & a_Client)
Do delaunay divide-and-conquer triangulation.
This algorithm can leave triangles that are VERY long and thin. The default ratio should be sufficient to get rid of these (on the exterior only). If you want to supply a bigger ratio to get rid of more triangles, you can, or you can do it on your own after you call this function.
Parameters
[in,out] a_Client Class used to help do the triangulation.
Returns
true if no errors.
Definition at line 2656 of file triangulate.cpp.
References xmlog::error, and XM_LOG.
Referenced by TrTriangulatorPointsUnitTests::test1(), and xms::TrTriangulator::Triangulate().
XmEdgesEquivalent()
bool xms::XmEdgesEquivalent (const XmEdge & a_edge1, const XmEdge & a_edge2)
Test if two edges are the same ignoring direction.
Parameters
a_edge1 The first edge to compare against.
a_edge2 The second edge to compare against.
Returns
True if two edges are same when indexes are in sorted order.
Definition at line 158 of file XmEdge.cpp.
References xms::XmEdge::IsEquivalent().
Referenced by XmEdgeUnitTests::testIsEquivalent().
XmReadUGridFromAsciiFile()
BSHP< XmUGrid > xms::XmReadUGridFromAsciiFile (const std::string & a_filePath)
Read XmUGrid from an ASCII file.
Parameters
[in] a_filePath filename to read including path, file name, and extension
Returns
the UGrid that was read from the file
Definition at line 779 of file XmUGridUtils - Copy.cpp.
References XmReadUGridFromAsciiFile(), and XmReadUGridFromStream().
Referenced by XmUGridUtilsTests::testWriteThenReadUGridFileToAscii(), and XmReadUGridFromAsciiFile().
XmReadUGridFromStream()
BSHP< XmUGrid > xms::XmReadUGridFromStream (std::istream & a_inStream)
Read an XmUGrid from ASCII text from an input stream.
Parameters
[in] a_inStream the stream to read
Returns
the UGrid
Definition at line 790 of file XmUGridUtils - Copy.cpp.
References daReadLine(), xmlog::error, XM_LOG, and XmReadUGridFromStream().
Referenced by XmUGridUtilsTests::testLargeUGridBinarySpeed(), XmUGridUtilsTests::testLinear2dWriteThenRead(), XmUGridUtilsTests::testLinear3dWriteThenRead(), XmUGridUtilsTests::testReadBasicUGrid(), XmUGridUtilsTests::testReadEmptyUGridAsciiFile(), XmUGridUtilsTests::testReadPolyhedronUGrid(), XmUGridUtilsTests::testReadReadyAtNextLine(), XmUGridUtilsTests::testReadVersion1Dot0File(), XmUGridUtilsTests::testWriteThenReadUGridBinary(), XmUGridUtilsTests::testWriteThenReadUGridFile(), XmReadUGridFromAsciiFile(), and XmReadUGridFromStream().
XmWriteUGridToAsciiFile()
void xms::XmWriteUGridToAsciiFile (BSHP< XmUGrid > a_ugrid, const std::string & a_filePath)
Write an XmUGrid to an ASCII file.
Parameters
[in] a_ugrid The UGrid to write to the file
[in] a_filePath filename to write including path, file name, and extension
Definition at line 847 of file XmUGridUtils - Copy.cpp.
References XmWriteUGridToAsciiFile(), and XmWriteUGridToStream().
Referenced by XmUGridUtilsTests::testWriteThenReadUGridFileToAscii(), and XmWriteUGridToAsciiFile().
XmWriteUGridToStream() [1/2]
void xms::XmWriteUGridToStream (BSHP< XmUGrid > a_ugrid, std::ostream & a_outStream)
Save an XmUGrid ASCII text to output stream.
Parameters
[in] a_ugrid the UGrid to save
[in] a_outStream the stream to write
Definition at line 857 of file XmUGridUtils - Copy.cpp.
References XmWriteUGridToStream().
Referenced by XmUGridUtilsTests::testLargeUGridBinarySpeed(), XmUGridUtilsTests::testLinear2dWriteThenRead(), XmUGridUtilsTests::testLinear3dWriteThenRead(), XmUGridUtilsTests::testWriteBasicUGrid(), XmUGridUtilsTests::testWriteEmptyUGrid(), XmUGridUtilsTests::testWriteLinear2dCells(), XmUGridUtilsTests::testWriteLinear3dCells(), XmUGridUtilsTests::testWritePolyhedronUGrid(), XmUGridUtilsTests::testWriteThenReadUGridBinary(), XmUGridUtilsTests::testWriteThenReadUGridFile(), XmWriteUGridToAsciiFile(), and XmWriteUGridToStream().
XmWriteUGridToStream() [2/2]
void xms::XmWriteUGridToStream (const XmUGrid & a_ugrid, std::ostream & a_outStream, bool a_binary)
Save an XmUGrid ASCII text to output stream.
Parameters
[in] a_ugrid the UGrid to save
[in] a_outStream the stream to write
[in] a_ugrid the UGrid to save
[in] a_outStream the stream to write
[in] a_binary should arrays be written in binary
Definition at line 866 of file XmUGridUtils - Copy.cpp.
References XmWriteUGridToStream().